### ISSUE TITLE
collaborate with future.apply?

### ISSUE THREAD

**Issue by r2evans** [DavisVaughan/furrr#1]
It seems that your code here are just another extension of [`HenrikBengtsson/future.apply`](https://github.com/HenrikBengtsson/future.apply) (as you stated in your readme).

https://github.com/HenrikBengtsson/future.apply/issues/9

**Comment by DavisVaughan** [comment]
Yes this code is directly related to future.apply. I haven't spoken with henrik yet, not sure if he's seen furrr yet. I'd be happy to help in adding support for other things / add furrr to the future extension collection, but parallel computing isn't my specialty so I'm not sure how much I'd be able to contribute.
