### ISSUE TITLE
Naming df  when using future_map2

### ISSUE THREAD

**Issue by JoeFernando** [DavisVaughan/furrr#10]
Hi Davis,

* I use a future_map2 to read a bunch of files (time reduced from 31 mins to 5 mins using a 8 core machine - amazing!)
* My issue is how to name the df, so that I can search for it by name within the returned list
* Example:

test <- function(x, name){
   require(tidyverse)
   z <- data.frame(x+1) %>% stats::setNames(., "a")
   return(z)
 }

furrr::future_map2(1:3, c("a", "b", "c"), ~test(.x, .y))

* I need a piece of code within the function that will give the df a name
* In the original function, some files are LARGE and other small, so reading times differ within files
* Hence, I am not sure if the dfs are jumbled within the list to use `names(list) <-  c("a", "b", "c")`

Any ideas?

Please HELP!

I have posted on SO:
https://stackoverflow.com/questions/50187445/how-to-name-a-name-a-dataframe-so-that-i-can-look-for-it-within-a-list#50187522

**Comment by DavisVaughan** [comment]
I'm not sure if this is a valid concern or not: `Hence, I am not sure if the dfs are jumbled within the list to use names(list) <- c("a", "b", "c")`. Haven't done enough testing to know if it's possible that things can be jumbled on the way back.

One cheap solution is to take advantage of attributes.

``` r
test <- function(x, name){
  require(tidyverse)
  z <- data.frame(x+1) %>% stats::setNames(., name)
  attr(z, "name") <- name
  return(z)
}

res <- furrr::future_map2(1:3, c("a", "b", "c"), ~test(.x, .y))
#> Loading required package: tidyverse

names(res) <- purrr::map_chr(res, ~attr(.x, "name"))

res
#> $a
#>   a
#> 1 2
#> 
#> $b
#>   b
#> 1 3
#> 
#> $c
#>   c
#> 1 4
```

Created on 2018-05-05 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by JoeFernando** [comment]
@DavisVaughan Thank you so much! Worked like magic 👍  
Although, the smaller files are read quicker and the larger ones trail, the return list is in the same order as the input, eg:
input.sequence(MASSIVE.FILE, Large.file, small.file, super.small.file) = Output sequence in the list 
Total read time down from 31 minutes to average of 6 mins 
Thanks again and Thanks for taking the time to put this package together 🥇
