### ISSUE TITLE
multiprocess crashes Rstudio

### ISSUE THREAD

**Issue by PMassicotte** [DavisVaughan/furrr#101]
I have read a few posts about that `multicore()` should not be used inside RStudio. When I use `multicore()` and then restart RStudio, it makes it crash. To be clear, RStudio does not restart correctly after I hit shift+ctrl+F10 if I do it after I called `plan(multiprocess(...))`.

![Peek 2020-01-21 11-08](https://user-images.githubusercontent.com/4519221/72821718-eb355000-3c3e-11ea-9d12-dde26bebd980.gif)

```r
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 19.3

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8   
 [6] LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2    yaml_2.2.0    
```

**Comment by DavisVaughan** [comment]
This is known behavior. Please see `?future::supportsMulticore()`. The defaults for `plan(multiprocess)` on a Mac in RStudio now choose multisession and warn you about this

**Comment by DavisVaughan** [comment]
I've never seen anything like that. Can you provide any more information at all?

**Comment by PMassicotte** [comment]
This is happening on my two Linux computers (at the job and at home). It only crashes if I use ctlr+shift+f10. If I close RStudio with alt-f4, RStudio closes _normally_ and nothing wrong is happening when I re-open it.

![Peek 2020-10-31 17-16](https://user-images.githubusercontent.com/4519221/97790232-410b3100-1b9d-11eb-95f5-0e2fde25c7eb.gif)

**Comment by DavisVaughan** [comment]
Try replacing `library(furrr)` with `library(future)`. Does the same thing happen?

**Comment by PMassicotte** [comment]
Yes.

**Comment by DavisVaughan** [comment]
Ping @HenrikBengtsson any advice?

**Comment by HenrikBengtsson** [comment]
It's RStudio and had nothing to do with the future framework, cf. https://github.com/rstudio/rstudio/issues/8141
