### ISSUE TITLE
Write stdout / stderr to local file?

### ISSUE THREAD

**Issue by mikekaminsky** [DavisVaughan/furrr#104]
Hi 👋  incredibly useful package. I am trying to figure out a way to check to make sure that a job I'm running with `furrr::future_map` is actually running on the remote machines I'm connected to but I'm struggling to figure out how to do this correctly.

When I set the `outfile` option in `future::makeClusterPSOCK` a log file is created on the remote machine which I can watch, but once I use `future_map` to submit the job, the logs are no longer directed to the local file on the remote machine, but instead are re-directed back to my local connection. The issue is that during this long-running process, the logs don't "flow" back to my local machine, they all arrive at once once the job completes.

Is there a way to achieve what I'm describing here? Or is this approach misguided?

**Comment by HenrikBengtsson** [comment]
This is per design in the future package.  However, there _might_ be some options for end-users to control in a future release (https://github.com/HenrikBengtsson/future/issues/294#issuecomment-477426168) but it'll take a while for such a feature to appear because it requires a deep investigation of what the side effects can be for other backends.

If you're interested in progress updated, then see the [progressr](https://cran.r-project.org/web/packages/progressr) package which will bring you near-live progress updates with futures.

**Comment by mikekaminsky** [comment]
Thanks for the update! Good to know. I might be able to hack something close to what I want using `sink` but we'll have to see (my use case is busting pretty far out of the bounds of what you've designed `future` for so it's hard to say if this would be useful for anyone else.

`progressr` looks very cool, but in my particular use case I think it'll be tricky to get working since my long-running process is a stan model and I'm not sure how I'd be able to get `progressr` sending back updates for that progress.

All of this is just in the interest of giving you additional context for my particular use case. I totally understand that might not lead to features since I'm doing some non-standard things :)

**Comment by HenrikBengtsson** [comment]
> progressr looks very cool, but in my particular use case I think it'll be tricky to get working since my long-running process is a stan model and I'm not sure how I'd be able to get progressr sending back updates for that progress.

{progressr} is designed to support sending progress updates (formally R conditions of class `progression` and `immediateCondition`) back to the master R process as soon as possible.  Currently, {future} backends 'sequential', 'multisession', and 'cluster' (local or remote) is aware of 'immediateCondition' and will relay them asap.  So, i think it'll do what you need if you're using one of those backends.  It's not hard to imagine other future backends will gain this skill too at some point.  This all described in details in the README on https://github.com/HenrikBengtsson/progressr/.

**Comment by mikekaminsky** [comment]
In case anyone else stumbles across this, I was able to achieve what I wanted by using `sink` inside the `future` call:

```
        job_futures[[conf_name]] <- future({
          print(paste0("Running job on remote box for: ", conf_name))
          sink(file = "~/log_name.log",
               append = FALSE, 
               type = c("output", "message"),
               split = TRUE)
          function_to_run(arg1, arg2)
          sink()
        })
```

**Comment by HenrikBengtsson** [comment]
FYI, `sink()`:ing with `type = "message"` (stderr) is unfortunately _not_ a reliable approach in R and it risks breaking thing.  From `?sink`:

> Sink-ing the messages stream should be done only with great care. For that stream file must be an already open connection, and **there is no stack of connections.**

For example, if `function_to_run()` or some function it calls would use `sink(..., type = "message")` internally, then your strategy would break.  For details and why this should be avoided, see https://github.com/HenrikBengtsson/Wishlist-for-R/issues/55.

**Comment by DavisVaughan** [comment]
I don't think there is much I can do on the furrr side here, so I'll close this one

**Comment by HenrikBengtsson** [comment]
> I don't think there is much I can do on the furrr side here ...

Correct, for those who follow this, this is something that should be handled at the core of futures, i.e. by the 'future' package.
