### ISSUE TITLE
Nested future

### ISSUE THREAD

**Issue by lrnv** [DavisVaughan/furrr#105]
Hey, 

I wander if there is an option to furrr or future that would allow me to nest `furrr::future_map` calls to re-distribute power to longer-running inner calls ? 

I was not sure where to post this, so i started by drafting a simple exemple there : https://stackoverflow.com/questions/61506909/nested-furrrfuture-map

**Q: How can i tell furrr to redispatch nested calls ? Can it even do this?**

**Comment by HenrikBengtsson** [comment]
This is explained in https://cran.r-project.org/web/packages/future/vignettes/future-3-topologies.html

**Comment by lrnv** [comment]
Yes i got it now. Thanks for the link, this does not need to stay open
