### ISSUE TITLE
Nesting future_pmap within future's %<-% to ensure console is available

### ISSUE THREAD

**Issue by al-obrien** [DavisVaughan/furrr#109]
I am looking for a way to use `furrr` functions that allows the main console to remain free until the future is called while still ensuring parallel processing occurs. 

When I run the following example dummy code, the process appears to run in parallel, but the console becomes locked until the entire process is complete.

```
library(glmnet)
library(dplyr)
library(purrr)

future::plan(multiprocess) 

grid  <- list(alpha = c(0,1),
              lambda = seq(from = 0, to = 0.1, by = 0.002)
              ) %>% 
  cross_df()

out <- {grid %>%
  mutate(fit = furrr::future_pmap(grid, ~glmnet(x =  model.matrix(Sepal.Length ~., iris)[,-1],
                                                y = iris$Sepal.Length, alpha = ..1, lambda = ..2)))}
```

I have used the `future` package before to allow the process to run in the "background" so that my console can remain free, but it does not appear to directly translate to use with `furrr`. The following allows the console to remain free but the process does not appear to run in parallel like it did before.
```
library(glmnet)
library(dplyr)
library(purrr)

future::plan(multiprocess) 

grid  <- list(alpha = c(0,1),
              lambda = seq(from = 0, to = 0.1, by = 0.002)
              ) %>% 
  cross_df()

# Using the future version of assignment
out %<-% {grid %>%
  mutate(fit = furrr::future_pmap(grid, ~glmnet(x =  model.matrix(Sepal.Length ~., iris)[,-1],
                                                y = iris$Sepal.Length, alpha = ..1, lambda = ..2)))}
```

Although this may be related to another [issue](https://github.com/DavisVaughan/furrr/issues/24), I was not aware of any solution found or if this is intended to be a feature at all. Perhaps I am missing something basic.

**Comment by HenrikBengtsson** [comment]
This is explained in https://cran.r-project.org/web/packages/future/vignettes/future-3-topologies.html

**Comment by al-obrien** [comment]
Thank you for directing me to this. It appears the 'single machine with 8 cores' is most relevant to my scenario and I will need to test out tweaks to `plan()` such as the following from the documentation:

`plan(list(tweak(multiprocess, workers = 2), tweak(multiprocess, workers = 4)))`
