### ISSUE TITLE
future_walk() and friends not available

### ISSUE THREAD

**Issue by mpickard-niu** [DavisVaughan/furrr#111]
Hi,

I've tried installing from CRAN and github, but I don't see the future_walk() functions available? All the map functions are available.

Here is my system info:
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock

**Comment by DavisVaughan** [comment]
They are definitely in the github version
