### ISSUE TITLE
Error in getGlobalsAndPackages(): Invalid future expression tries to use global '...'

### ISSUE THREAD

**Issue by MatthieuStigler** [DavisVaughan/furrr#114]
I was running into an error: *Error in getGlobalsAndPackages(expr, envir = envir, globals = TRUE) : 
  Did you mean to create the future within a function?  Invalid future expression tries to use global '...'*, and finally nailed it down to a reprex (not sure it's the most minimal reprex though...). 

It seems that if I am using `future_map` over a function that iteself uses a `map` call invoked with a function that contains the `...`, this triggers the message above? Indeed either running `map` only or using `future_map` on the function without `...` work, but as soon as one adds this the error shows up?

Thanks!! 

``` r
library(tidyverse)
library(furrr)
#> Loading required package: future
packageVersion("furrr")
#> [1] '0.1.0.9002'
packageVersion("future")
#> [1] '1.18.0'


iris_ns <- iris %>% 
  as_tibble() %>% 
  nest(data= -Species)


fo_prob <- function(df, ...){
  
  tibble(input=1:3) %>% 
    mutate(out= map(input, ~lm(Sepal.Length ~ Sepal.Width, data=df, ...)))
}

fo_ok <- function(df, ...){
  
  tibble(input=1:3) %>% 
    mutate(out= map(input, ~lm(Sepal.Length ~ Sepal.Width, data=df)))
}


out <- future_map(iris_ns$data, fo_ok)
out2 <- map(iris_ns$data, fo_prob)
future_map(iris_ns$data, fo_prob)
#> Error in getGlobalsAndPackages(expr, envir = envir, globals = TRUE): Did you mean to create the future within a function?  Invalid future expression tries to use global '...' variables that do not exist: .f()
```

**Comment by DavisVaughan** [comment]
I don't think the dots here are doing what you think they are doing. The `...` don't get passed into the anonymous function created by `~` in purrr. They instead correspond to a catch all for `.x`. Notice how `foo = "haha"` doesn't appear here, but all the `.x` elements are caught

``` r
library(purrr)

catcher <- function(x, ...) {
  map(x, ~list(...))
}

map(list(1:2, 1:3), catcher, foo = "haha")
#> [[1]]
#> [[1]][[1]]
#> [[1]][[1]][[1]]
#> [1] 1
#> 
#> 
#> [[1]][[2]]
#> [[1]][[2]][[1]]
#> [1] 2
#> 
#> 
#> 
#> [[2]]
#> [[2]][[1]]
#> [[2]][[1]][[1]]
#> [1] 1
#> 
#> 
#> [[2]][[2]]
#> [[2]][[2]][[1]]
#> [1] 2
#> 
#> 
#> [[2]][[3]]
#> [[2]][[3]][[1]]
#> [1] 3
```

<sup>Created on 2020-08-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm not entirely sure why it errors, but I don't think this is a furrr bug. If anything it is with future checking the `...` usage. I'll try and open an issue there if it applies
