### ISSUE TITLE
ERROR : first argument (nc) is not of class ncdf4! 

### ISSUE THREAD

**Issue by solomonsg** [DavisVaughan/furrr#140]
Hi all, 

I have a NetCDF file with more than 100000 files merged by ID (1-100000). For each file in the NetCDF, I am computing some statistics and the code works before  future_map but after modifying the code for parallel processing I am getting an error. this is my first time using furrr and I think there is a problem in my code. 

         ncprcp <- nc_open("global_prc.nc")
         rivid <- ncvar_get(ncprcp, "ID")

     runfile <- function (ncprcp) {
         for (i in 1:length(rivid)) {
           sflow <- ncvar_get(ncprcp, varid = "prcp", start = c(i, 1), count = c(1, -1))
           times <- ts(sflow, start=1981)
          mk = mk.test(times)
          IDname <- ID[i]
         merged <- data.frame(IDname, mk$p.value)
         }
    }
      plan(multiprocess)
     allfile <- future_map_dfr(ncprcp, runfile, .progress=TRUE)
     write.csv(allfile, "para_test_prcp.csv")

Finally, I am getting the following error.                      ERROR : first argument (nc) is not of class ncdf4! 
Best, SG

**Comment by DavisVaughan** [comment]
It looks like `nc_open()` is opening some kind of file connection. That probably can't easily be serialized and exported to a worker. File connections are one type of non-exportable object. See https://cran.r-project.org/web/packages/future/vignettes/future-4-non-exportable-objects.html

There is nothing we can do about that in furrr unfortunately

**Comment by Anaye144** [comment]
I have a folder containing NetCDF files with more than 180
NetCDF files. For each file, there are 14 parameters.
I would just like to extract a specific parameter from the 14 parameters of each of the 180 files.
And join the extracted files.

rm(list = ls())
library("ncdf4")
library("dplyr")
library("raster")
setwd("D:/donnees/JJASNCDATA")
fichier<- list.files(pattern = ".nc")
mfichier<-lapply(fichier, nc_open)
for (n in 1:length(fichier)) {
  fdata[n]<-ncvar_get(mfichier[n],varid = "Rain")
}

RR_pluie<-left_join(fdata[1:n])

Finally, I am getting the following error. ERROR : first argument (nc) is not of class ncdf4!

Anaye!

**Comment by DavisVaughan** [comment]
This issue is not related to furrr. Please only ask furrr related questions on this github repo.

You may need `mfichier[[n]]` rather than `mfichier[n]`.
