### ISSUE TITLE
question about parallel inside a parallel

### ISSUE THREAD

**Issue by kurt1984** [DavisVaughan/furrr#170]
can we do parallel inside a parallel

plan(multisession, workers = 3)
result_out_combined <- future_map(1:num_ptn, function(x){
  plan(multisession, workers = 3)
  future_map(1:10, mean)
)

**Comment by DavisVaughan** [comment]
The correct way to do this is by providing a list of plans to `plan()`, but there is a lot to say here, so please read https://cran.r-project.org/web/packages/future/vignettes/future-3-topologies.html for more
