### ISSUE TITLE
Don't use random numbers in examples without specifying a seed

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/furrr#172]
i.e. look for more examples of this and fix them:
https://davisvaughan.github.io/furrr/reference/future_map.html#examples

**Comment by HenrikBengtsson** [comment]
FYI, if you set env var `R_FUTURE_RNG_ONMISUSE="error"`, then these warnings will turn into errors.  I've got a Travis CI job that runs with that.
