### ISSUE TITLE
How to make future_walk() non-blocking?

### ISSUE THREAD

**Issue by privefl** [DavisVaughan/furrr#178]
I would like to use packages {future.batchtools} and {furrr} to run loops in parallel on some HPC cluster.
In my loops, I save each result in some RDS file, and basically return nothing.
Is there any way to run `future_walk()` for this that would be non-blocking, i.e. once jobs for each element of the loop has been scheduled, then the R session becomes free again.

**Comment by DavisVaughan** [comment]
There is no way to do this with furrr, but you can use `future::future()` directly alongside a simple for loop to achieve this

I don't believe it makes sense for furrr to have a non blocking mode.
