### ISSUE TITLE
workers built but not operating

### ISSUE THREAD

**Issue by stemangiola** [DavisVaughan/furrr#179]
in a future_pmap call the workers get build over couple of minutes (likely for the big amount of data). However, after the memory imprint is done, they never start procesing

![image](https://user-images.githubusercontent.com/7232890/97819316-de7c7700-1cfb-11eb-94e6-c6cd73298c0a.png)

Code executed

```
	expand_grid(S = 1:(dim(draws_mu)[2]), G = 1:(dim(draws_mu)[3])) %>%
		mutate(truncation_compensation = !!truncation_compensation) %>%
		mutate(
			CI = pmap(
				list(  S,G, truncation_compensation),
				~ tibble(
					mu = draws_mu[,..1, ..2],
					sigma = draws_sigma[,..2]	,
					exposure = draws_exposure[,..1],
					truncation_compensation = ..3
				) %>%
				get_CI_semi_analytically_pnbinom(	adj_prob_theshold	) %>%

				# Add mean and sd
				dplyr::mutate(
					mean = mean(exp(draws_mu[,..1, ..2] + draws_exposure[,..1])),
					sd = mean(1/exp(draws_sigma[,..2]) * truncation_compensation)
				)
			)
		)

```

**Comment by DavisVaughan** [comment]
I'm not entirely sure what you are saying here.

Does the code you are running finish and return a result?

What OS are you on?

Are you using `plan(multisession)`?

---

Also, this isn't really a reproducible example

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by stemangiola** [comment]
Sorry I just haven't had time for building a proper reprex. If I have more info I will open the issue again.

Thanks.
