### ISSUE TITLE
show progress bar for sequential execution

### ISSUE THREAD

**Issue by tklebel** [DavisVaughan/furrr#18]
Especially if the user is unsure about how long a query will take, it would be great if a progress bar could be displayed even for sequential execution. 

I guess there is a reason why it is not implemented for sequential backends, but it would still be great to have it! :smile:

**Comment by DavisVaughan** [comment]
I totally hear you, but it's actually a bit challenging. It has to do with when the main R process is "blocked" when running in parallel vs sequential. Long story short, the way it is currently set up will block the main R session when you run sequentially, and the code that checks for progress bar updates will only run AFTER the iterations are all completed, so...useless at that point.

I'll keep thinking about this, but to be transparent it's not on my short term to do list!

**Comment by DavisVaughan** [comment]
The progress bar is going to be deprecated in the next release, so this won't be implemented. Instead, look to the {progressr} package which supersedes the progress bar and can be used in sequential or parallel mode.
