### ISSUE TITLE
AWS connection not running in parallel

### ISSUE THREAD

**Issue by graemeleehickey** [DavisVaughan/furrr#180]
Running the simple toy example using `future_map` takes the same amount as running with `purrr::map` on an AWS EC2 instance with 64 cores.

```r
library(purrr)
library(furrr)
library(tictoc)

public_ip <- "x.xxx.xx.xxx" # hidden for purposes of reprex
ssh_private_key_file <- "myfile.pem"

connect_to_ec2 <- function(public_ip, ssh_private_key_file) {
  makeClusterPSOCK(
    
    # Public IP number of EC2 instance
    workers = public_ip,
    
    # User name (always 'ubuntu')
    user = "ubuntu",
    
    # Use private SSH key registered with AWS
    rshopts = c(
      "-o", "StrictHostKeyChecking=no",
      "-o", "IdentitiesOnly=yes",
      "-i", ssh_private_key_file
    ),
    
    # Switch this to TRUE to see the code that is run on the workers without
    # making the connection
    dryrun = FALSE
  )
}

cl <- connect_to_ec2(public_ip, ssh_private_key_file)
cl

# Socket cluster with 1 nodes where 1 node is on host ‘x.xxx.xx.xxx’ (R version 4.0.3 (2020-10-10), platform x86_64-pc-linux-gnu)

plan(cluster, workers = cl)

tic()
future_map(1:10, ~{ Sys.sleep(5) })
toc() # 51.358 sec

tic()
map(1:10, ~{ Sys.sleep(5) })
toc()  # 50.015 sec
```

I'm not sure if I am setting this up incorrectly. Any advice would be appreciated.

**Comment by DavisVaughan** [comment]
So you have 1 worker that has 64 cores? It sounds like you need to do _nested_ parallelism. The first layer of parallelism distributes across your workers (here you only have 1 worker, you are currently doing this layer of parallelism). The second layer distributes across the cores on each worker (ie the 64 cores). Right now it seems like you are doing the first but not the second. Have a look at this vignette for more info https://davisvaughan.github.io/furrr/articles/articles/remote-connections.html#running-code-in-parallel-on-each-ec2-instance

**Comment by DavisVaughan** [comment]
there is also a very useful section on this in the r cookbook https://rc2e.com/usefultricks#recipe-parallel_remote, thanks @CerebralMastication!

**Comment by graemeleehickey** [comment]
Thank you! That was exactly the issue. I needed the second parallelisation with `multisession` to utilise all the cores.
