### ISSUE TITLE
feature request: future_map2_df 

### ISSUE THREAD

**Issue by edreddick** [DavisVaughan/furrr#189]
Hi there,

I'm interested in using furrr to speed up some code I wrote using purrr. Are there plans to write a **_furrr::future_map2_df_** function similar to **_purrr::map2_df_**?

I noticed that furrr already has corresponding functions of purrr's **_map2_dfr_**, and **_map2_dfc_**, but not **_map2_df_**.

Thanks for your work on this cool package!

**Comment by DavisVaughan** [comment]
`map2_dfr()` is the same as `map2_df()`. So just use `future_map2_dfr()`!

purrr no longer recommends using `map2_df()`, since `map2_dfr()` is a bit more descriptive about what is happening, so I don't feel any need to add a `future_map2_df()` alias

**Comment by edreddick** [comment]
Sounds good, thank you!
