### ISSUE TITLE
Nested futures

### ISSUE THREAD

**Issue by artichaud1** [DavisVaughan/furrr#19]
Hey Davis,
this is a question really.
In your aws.ec2 script (https://gist.github.com/DavisVaughan/5aac4a2757c0947a499d25d28a8ca89b), on line 113, we are sending tasks to each node of the cluster.
Is it possible to use a plan(multiprocess) inside each node so that the task received is run in parallel (multicore) ?
In my case (hyperparameter tuning), what I would like to do is send the folds to different machines, but then on each machine do the parameter search in parallel.
I think I saw a mention of something like this on the future vignette, but would like to get your input on it (and how it would be done in furrr).
Thx !

**Comment by DavisVaughan** [comment]
I had the same thought. See the last comment on https://gist.github.com/DavisVaughan/865d95cf0101c24df27b37f4047dd2e5
