### ISSUE TITLE
Furrr Save to Excel Issue

### ISSUE THREAD

**Issue by bewadver** [DavisVaughan/furrr#191]
Hi there,
I am a beginner and using R to:
1. Generate pivot tables and 
2. export them to Excel

Because of the large number of the tables I am using furrr to enhance the performance. The issue I have met:  With pmap all the tables can be rendered and saved to Excel. With future_pmap only partial tables, or even no tables are saved to Excel. Please see my code attached for illustration the issue.  You can run the code directly, the only adjustment is the path of the Excel file. 
[Furrr Save to Excel Issue.docx](https://github.com/DavisVaughan/furrr/files/6289748/Furrr.Save.to.Excel.Issue.docx)

Very appreciated if someone could help? I need to know:
How should I set the future plan to export all the pivot tables to Excel, at the same time to really enhance the performance?
BR

**Comment by DavisVaughan** [comment]
This is likely just not a thread safe activity. I imagine that multiple cores are opening up the same file at the same time, trying to write to it, and are then individually saving over each other.

Now, if each call to `pivot()` wrote data into a different workbook, it would probably work.

But repeatedly opening, writing to, and saving the same workbook in parallel is unfortunately something that is unlikely to work correctly. This is a general problem when writing to any type of file, not just excel files.

I think my only advice to you is to use `pmap()` for something like this

**Comment by DavisVaughan** [comment]
Also, GitHub allows you to post your code directly in the Issue box. 

If you type three backticks, then another three backticks, you can place code inside that and it will be rendered nicely. Also, if you place an `r` after the first set of three backticks, it will color the code like R code

``````
```r
# code goes here
```
``````

Here is what your word document would look like:

```r
library(tidyverse) 
library(lubridate)
library(openxlsx)
library(pivottabler)
library(furrr) 
library(here)
library(tictoc)

future::plan(multisession(workers=2, packages=c('pivottabler', "openxlsx")))

trains <- bhmtrains[ , 2:4]

train_list <- split(
  trains, 
  trains$Status,
  lex.order=TRUE
)

furrr_pivotinput <- tribble(
  ~ Status,   ~ rowno,   ~ colno,   ~ df,
  "A", 3, 2, "trainlist",
  "C", 13, 2, "trainlist",
  "R", 23, 2, "trainlist"
)

purrr_pivotinput <- tribble(
  ~ Status,   ~ rowno,   ~ colno,   ~ df,
  "A", 3, 10, "trainlist",
  "C", 13, 10, "trainlist",
  "R", 23, 10, "trainlist"
)

furrr_pivotinput <- furrr_pivotinput %>% 
  mutate(df = train_list)
purrr_pivotinput <- purrr_pivotinput %>% 
  mutate(df = train_list)

tf <- tempfile(fileext = ".xlsx")

Test <- createWorkbook()
addWorksheet(Test, "Purrr or Furrr", gridLines = FALSE)
file_test <- tf
saveWorkbook(
  Test, 
  file = file_test, 
  overwrite = TRUE
)

pivot <- function(Status, rowno, colno, df){
  pt <- PivotTable$new()
  pt$addData(df) 
  pt$addColumnDataGroups("TrainCategory")
  pt$addRowDataGroups("TOC")
  pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
  pt$renderPivot()
  
  pt$writeToExcelWorksheet(
    wb = Test, 
    wsName = "Purrr or Furrr", 
    topRowNumber = rowno, 
    leftMostColumnNumber = colno,
    applyStyles = TRUE, 
    mapStylesFromCSS = TRUE
  )
  
  writeData(Test, 
            "Purrr or Furrr", 
            Status,
            startCol = colno, 
            startRow = rowno - 1)
  
  saveWorkbook(
    Test, 
    file = file_test, 
    overwrite = TRUE
  )  
}

# Should export pivot tables to Excel, but only work properly when using sequential plan
tic()
future_pmap(
  furrr_pivotinput, 
  pivot,
  .options = furrr_options(seed = 123))
toc()

# For comparing with the future_pmap to see the expected results
tic()
pmap(purrr_pivotinput, pivot)
toc()
```

**Comment by bewadver** [comment]
Thank you so much Davis for your reply! Nice weekend and BR
