### ISSUE TITLE
furrr interferes with the {crayon} and {cli} messages colors

### ISSUE THREAD

**Issue by gorkang** [DavisVaughan/furrr#192]
As you can see in the image below, when using furrr, the console stops printing colors, at least with the {crayon} and {cli} packages. 
 

![Screenshot from 2021-04-23 21-00-15](https://user-images.githubusercontent.com/6491790/115923945-f2b55b80-a476-11eb-835b-12f6ee6252f4.png)

A simple reproducible example:

``` r
library(future)
library(future.callr)
future::plan(callr)

fnx <- function(number) {
  cat(crayon::yellow(paste0("Running task ", number, "\n")))
  cli::cli_alert_success("Running task {number}")
}

fnx(1)
#> Running task 1
#> ✓ Running task 1

furrr::future_walk(1, fnx)
#> Running task 1
#> ✓ Running task 1
#> Warning: UNRELIABLE VALUE: Future ('<none>') unexpectedly generated random
#> numbers without specifying argument 'seed'. There is a risk that those random
#> numbers are not statistically sound and the overall results might be invalid.
#> To fix this, specify 'seed=TRUE'. This ensures that proper, parallel-safe random
#> numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use
#> 'seed=NULL', or set option 'future.rng.onMisuse' to "ignore".
```

<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Thanks!

**Comment by DavisVaughan** [comment]
This isn't a furrr thing, future controls how output is relayed. 

```r
library(future)
library(future.callr)
future::plan(callr)

fnx <- function(number) {
  cat(crayon::yellow(paste0("Running task ", number, "\n")))
  cli::cli_alert_success("Running task {number}")
}

fnx(1)

value(
  future({
    fnx(1)
  }, 
  seed = 123)
)
```

Produces:

<img width="492" alt="Screen Shot 2021-04-24 at 12 04 47 PM" src="https://user-images.githubusercontent.com/19150088/115965093-7d3ca000-a4f5-11eb-957f-a9bd432c436e.png">

@HenrikBengtsson any thoughts on this?

**Comment by HenrikBengtsson** [comment]
Roughly: **crayon** disable coloring in non-interactive R sessions. Parallel R workers run in non-interactive R processing. This is not unique to **future**; you'll get the same if you run a script with say `Rscript myscript.R`.  I think ?crayon::num_ansi_colors has the details.

Setting `options(crayon.enabled=TRUE)` _inside_ future expression will re-enable it.  Another alternative would be to set:

```r
Sys.setenv(R_CLI_NUM_COLORS = crayon::num_ansi_colors())
```

ones, but not sure if there are downsides to that.  /cc @gaborcsardi

**Comment by gorkang** [comment]
Thanks Davis and Henrik!

`Sys.setenv(R_CLI_NUM_COLORS = crayon::num_ansi_colors())` seems to work well in the _targets.R file in {targets}. @wlandau , pinging you in case you want to mention this in the manual, or maybe can think of any downside of this approach.

**Comment by wlandau** [comment]
Seems like a good workaround to me.

There are tradeoffs when it comes to `crayon` colors because sometimes ANSI sequences are printed literally instead of rendered as the colors we expect: https://cran.r-project.org/web/packages/fansi/vignettes/sgr-in-rmd.html. I try to balance that in`targets`: https://github.com/ropensci/targets/discussions/302.
