### ISSUE TITLE
How to suppress naming messages

### ISSUE THREAD

**Issue by 1beb** [DavisVaughan/furrr#201]
The following shows up when using `futurue_map_dfc` or others. Is there a way to supress the messages? Or is there an argument that allows you to name them within the function? (Right now I'm chaining `%>% setNames(...)`)

```
New names:
* NA -> ...1
* NA -> ...2
* NA -> ...3
* NA -> ...4
* NA -> ...5
* ...
```

**Comment by DavisVaughan** [comment]
I imagine you would also get the name repair when working with `purrr::map_dfc()` too right? If each call to `.f` returns a single vector, you could name `.x` and then the returned data frame will have column names matching the names of `.x`.

``` r
x <- 1:5

purrr::map_dfc(x, identity)
#> New names:
#> * NA -> ...1
#> * NA -> ...2
#> * NA -> ...3
#> * NA -> ...4
#> * NA -> ...5
#> # A tibble: 1 x 5
#>    ...1  ...2  ...3  ...4  ...5
#>   <int> <int> <int> <int> <int>
#> 1     1     2     3     4     5

furrr::future_map_dfc(x, identity)
#> New names:
#> * NA -> ...1
#> * NA -> ...2
#> * NA -> ...3
#> * NA -> ...4
#> * NA -> ...5
#> # A tibble: 1 x 5
#>    ...1  ...2  ...3  ...4  ...5
#>   <int> <int> <int> <int> <int>
#> 1     1     2     3     4     5

x <- 1:5
names(x) <- letters[1:5]

purrr::map_dfc(x, identity)
#> # A tibble: 1 x 5
#>       a     b     c     d     e
#>   <int> <int> <int> <int> <int>
#> 1     1     2     3     4     5
```

<sup>Created on 2021-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by 1beb** [comment]
I did not realize that it would carry the names through. Thank you for this.
