### ISSUE TITLE
Appreciation for furrr

### ISSUE THREAD

**Issue by JZL** [DavisVaughan/furrr#202]
Hi,

I'll immediately close this issue but I wanted to let you know how much I enjoy and use `furrr`. I use it constantly throughout the day and it's baked into all of my scripts now. It's one of the first things I install on a few R environment!

I pretty much only use map/future_map now and often rent 20+ core VM's so it has saved me a truly unbelievable amount of time

Thanks!

**Comment by DavisVaughan** [comment]
I'm happy to hear that! Thanks for letting me know!
