### ISSUE TITLE
Suggestion: improving progress reporting, particularly in nested futures?

### ISSUE THREAD

**Issue by angel-bee2018** [DavisVaughan/furrr#208]
Hi! First of all I want to say thank you so much for continuing to develop furrr. I would be nowhere without it right now.

I make use of nested futures pretty often, and i have been wondering whether there are plans to improve the way task progress is currently reported? 
What I have in mind are two things which would improve clarity and debugging:
1. Allowing each nested future to report its progressbar in _real time_, and,
2. A detailed "tree" view (much like the output of `str`) which shows the progress bars of all running processes in a hierarchical layout, so we can better track the child processes and their parents.

Would it be easy to implement these changes? Something like this would mean that we won't have to indirectly track the running tasks in `top` or `task manager` which also gets confusing when running multiple R sessions which are all running furrr.

p.s. apologies if these things have already beeen mentioned before, and i wasn't aware.

**Comment by DavisVaughan** [comment]
I have no plans to add more progress bar support to furrr. 

In fact, I plan to eventually deprecate progress bar support in favor of using the progressr package (also by the future maintainer). It will eventually supported nested futures if it doesn't already. You can read a little about the package + furrr here https://furrr.futureverse.org/articles/articles/progress.html
