### ISSUE TITLE
Error when using batchtools futures and progress bar

### ISSUE THREAD

**Issue by kendonB** [DavisVaughan/furrr#23]
Can't give a MWE as I as testing this on a slurm cluster. 
```r
my_list %>%
  future_map(~{my_fun}, .progress = TRUE)
Error in mutate_impl(.data, dots) :
  Evaluation error: BatchtoolsError in BatchtoolsFuture ('<none>'): ‘Error in file(temp_file, "a") : cannot open the connection’.
```
Maybe @mllg can immediately see what's going on or if the ``furrr`` progress bar can't work with batchtools.

**Comment by DavisVaughan** [comment]
furrr cannot work with remote clusters + progress bars with the current implementation. It needs to be able to write to a local file on Master from each Node. I've tried to state this by saying in the docs somewhere that the progress bar only works for multicore multiprocess and multisession

**Comment by kendonB** [comment]
This sounds feasible for batchtools then? batchtools writes stdout to text files, for example, and the host process has access to the same file system as the nodes. Perhaps I'm confused by what Master means here.

**Comment by DavisVaughan** [comment]
Master in this case means your local computer, sorry. Where you call furrr from. I don't think in ever case you'd have access to that from your local computer. I also don't have enough experience to write or test that kind of thing

**Comment by kendonB** [comment]
So yes in this case I'm calling furrr from an interactive session on the cluster, connected via ssh.

**Comment by mllg** [comment]
My best guess: The registry is created in a directory (see `future.batchtools:::future_cache_path()`) which is not shared across nodes. Can you provide a `traceback()`?
