### ISSUE TITLE
Would future::plan() work if embedded in a function?

### ISSUE THREAD

**Issue by EvoLandEco** [DavisVaughan/furrr#237]
```r
### case 1
fun_that_sets_plan <- function(strategy, workers) {
    future::plan(strategy, workers)
}
furrr::future_map(things)
###

### case 2
future::plan(strategy, workers)
furrr::future_map(things)
###
```
I would like to know if case 1 works as case 2, that I put `future::plan` inside another function?

**Comment by jinyancool** [comment]
I donot think that case 1 works as case 2. But it will be easy test it.

**Comment by EvoLandEco** [comment]
@jinyancool I tried and it worked, It would be much appreciated if you could also try and confirm it
