### ISSUE TITLE
furrr::future_map  could not find function 

### ISSUE THREAD

**Issue by 13479776** [DavisVaughan/furrr#245]
Hi, guys,

I used the   furrr::future_map for list data processing. The error was happened that a function named mf could not be found, although m and mf function have been loaded in the R environments (I enter the m or mf into console, and the code can be shown)

```
require(furrr)
    future::plan(multisession, workers = 2)
msScore <- furrr::future_map(x, m, .options = furrr_options(pseed = 123))

Error in m(..  : 
  could not find function "mf"
Called from: signalConditions(obj, exclude = getOption("future.relay.immediate", 
    "immediateCondition"), resignal = resignal, ...)
```

Could you please give some suggestion?  if i use the purrr::map, the problems was missing.

Thanks

hees

**Comment by DavisVaughan** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by 13479776** [comment]
Hi DavisVaughan，

     I use the reprex to trace the code. The reprex could not process the developing package under devtools. so, I built the package and found the problems were missing. I guess the furrr require the package have been built and installed in the R. Is it right?

thanks

Hees

**Comment by DavisVaughan** [comment]
Yea you need to install the package you are developing for it to be available on other workers and for furrr to be able to find functions from it
