### ISSUE TITLE
furrr should never evaluate arguments to .f early (i.e. use in NSE)

### ISSUE THREAD

**Issue by EdJeeOnGitHub** [DavisVaughan/furrr#25]
Hi,
I seem to be having an issue with dplyr's quasiquotation in furrr that doesn't occur in purrr. 

This is a pretty niche example and I'm sure there's a better way of doing this without using the `dummy_argument` set up but presumably the functionality between the two packages should be similar regardless.

```
library(dplyr)
library(purrr)
library(furrr)
plan(multiprocess)

df_1 <- data.frame(neighbour_pet = c('horse', 'rattlesnake', 'cat'),
                   my_pet = c('dog', 'cat', 'mouse'))

filter_function <- function(data, filter_var, dummy_argument){
  filter_var <- enquo(filter_var)
  
  ## Stuff happens here ##
  
  
  data <- data %>% 
    filter(!!filter_var == 'dog')
  return(data)
}

df_filtered_purrr <- 1:100 %>% 
  map(filter_function, filter_var = my_pet, data = df_1)


df_filtered_furrr <- 1:100 %>% 
  future_map(filter_function, filter_var = my_pet, data = df_1)

```
`df_filtered_purrr` works fine whilst `df_filtered_furrr` leads to this error:

> Error in do.call(call, args = c(list(".f"), list(...))) : 
>   object 'my_pet' not found

In reality I'm running simulations with slightly different data each time and I need to use `filter` within the `filter_function` after I've perturbed the data. This isn't a big issue as I can just use `map` but thought it best to share - I tried using `future_options` but it wasn't immediately obvious to me what to do - apologies if this is just a result of my incompetence.

Thanks for all your work on the package!

**Comment by DavisVaughan** [comment]
I agree with you that this is a bug, and it is one that I have run into before. Luckily there is an easy temp solution. Call the function using the formula interface, specifying the quasiquotated args inside the function itself.

```r
df_filtered_furrr <- 1:100 %>% 
  future_map(~filter_function(filter_var = my_pet, data = df_1))
```

The error has to do with the way that `furrr` looks for variables to automatically export. It sees `filter_var = my_pet` and tries to evaluate `my_pet` immediately but that does not exist as a variable so things fail. I'd like to rework this eventually so I'll leave the issue open, but this should help for now

**Comment by hadley** [comment]
FWIW, I think that this behaviour is not a bug. The contract for furrr, like for purrr, should be that `map()` functions evaluate their arguments; if you don't want that behaviour you should use an anonymous function.

**Comment by hadley** [comment]
In particularly, note the difference here:

``` r
library(purrr)

plus <- function(x, y) x + y

map(1:2, plus, runif(1))
#> [[1]]
#> [1] 1.426515
#> 
#> [[2]]
#> [1] 2.426515
map(1:2, ~ plus(.x, runif(1)))
#> [[1]]
#> [1] 1.388924
#> 
#> [[2]]
#> [1] 2.914707
```

Created on 2018-08-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by DavisVaughan** [comment]
This example makes sense to me (and is a really neat nuance to `purrr` use) but shouldn't the behavior of `furrr` and `purrr` still match in the original example presented? 

Essentially, `furrr` tries to eval `my_pet` too early, outside the context of the `df_1` data frame, while `purrr` (from what I can tell) never evaluates `my_pet` until [this forceAndCall()](https://github.com/tidyverse/purrr/blob/master/src/map.c#L45) call where it is in the context of the data frame so things work fine there.

**Comment by hadley** [comment]
Right - I think you should try and avoid evaluating while you're looking for global variables, but I don't _think_ you should avoid evaluating the dots when sending to another process. 

This is another difference between sequential and parallel code - if you're distributing the task there's no way to ensure that the dot arguments are evaluated lazily and only once. I think it's better to preserve the evaluated once property than the laziness property.

**Comment by DavisVaughan** [comment]
Documenting an example of how to avoid evaluating while looking for globals so I dont forget

```r
library(furrr)

# find this function as a global to export
get_me <- function() {
  print("hi")
}

top_fn <- function() {
  get_me()
}

debugonce(furrr:::gather_globals_and_packages)

# be able to iterate over ... to capture the globals in top_fn,
# but don't evaluate bare_column_name which could be used in a mutate()
# or something
future_map(1:5, mean, na.rm = top_fn, blah = bare_column_name)

# While debugging gather_globals_and_packages()
# do this to capture globals without evaluating
# getGlobalsAndPackages(lapply(rlang::quos(...), rlang::quo_squash), envir = envir)
```
