### ISSUE TITLE
Carrier

### ISSUE THREAD

**Issue by instantkaffee** [DavisVaughan/furrr#255]
https://github.com/r-lib/carrier Is reported to be superseeded.
https://furrr.futureverse.org/articles/carrier.html docu builds on it.

Any sustinable solution?

**Comment by lionel-** [comment]
Superseded means it's super stable, we'll maintain it without changing it ever. So it's a very sustainable option.

**Comment by lionel-** [comment]
After discussion with Davis, we decided to switch the lifecycle state back to "stable" since there is no alternative to carrier for furrr
