### ISSUE TITLE
cpu utilization

### ISSUE THREAD

**Issue by topepo** [DavisVaughan/furrr#3]
I'm seeing some weird cpu utilization when `future_map` is called more than once. 

First, the speed-up on the first parallel execution is about 1.77-fold (163.6s sequential vs 92.2s parallel with _20 cores_ via `plan(multiprocess)`). Looking at the cpu utilization, the work seems largely over in about 27s with some workers bouncing around a bit at the end. 

The second parallel execution takes 135.6s for a 1.20-fold speed-up. That cpu usage is very strange and exhibits a similar "bouncy" phase at the end. 

![cpu](https://user-images.githubusercontent.com/5731043/38788010-5bb14204-40ff-11e8-94b1-c676f1dd7465.jpeg)

All the code and data are attached. 

[furrr_benchmark.zip](https://github.com/DavisVaughan/furrr/files/1913731/furrr_benchmark.zip)

Let me know if you need more information. 

```r
> availableCores()
system 
    20 
> session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 os       macOS High Sierra 10.13.3   
 system   x86_64, darwin15.6.0        
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-04-15                  

─ Packages ───────────────────────────────────────────────────────────────────
 package     * version    date       source                             
 abind         1.4-5      2016-07-21 CRAN (R 3.4.0)                     
 AmesHousing * 0.0.3      2017-12-28 Github (topepo/AmesHousing@97bb8cc)
 assertthat    0.2.0      2017-04-11 CRAN (R 3.4.0)                     
 bindr         0.1        2016-11-13 CRAN (R 3.4.0)                     
 bindrcpp      0.2        2017-06-17 CRAN (R 3.4.0)                     
 broom       * 0.4.4      2018-03-29 CRAN (R 3.4.3)                     
 class         7.3-14     2015-08-30 CRAN (R 3.4.3)                     
 clisymbols    1.2.0      2017-05-21 CRAN (R 3.4.0)                     
 codetools     0.2-15     2016-10-05 CRAN (R 3.4.3)                     
 colorspace    1.3-2      2016-12-14 CRAN (R 3.4.0)                     
 CVST          0.2-1      2013-12-10 CRAN (R 3.4.0)                     
 ddalpha       1.3.2      2018-04-08 cran (@1.3.2)                      
 DEoptimR      1.0-8      2016-11-19 CRAN (R 3.4.0)                     
 digest        0.6.15     2018-01-28 cran (@0.6.15)                     
 dimRed        0.1.0.9001 2018-03-20 local (topepo/dimRed@NA)           
 dplyr       * 0.7.4      2017-09-28 CRAN (R 3.4.2)                     
 DRR           0.0.3      2018-01-06 cran (@0.0.3)                      
 foreign       0.8-69     2017-06-22 CRAN (R 3.4.3)                     
 furrr       * 0.1.0      2018-04-14 Github (DavisVaughan/furrr@ff33338)
 future      * 1.8.0      2018-04-08 cran (@1.8.0)                      
 geometry      0.3-6      2015-09-09 cran (@0.3-6)                      
 ggplot2       2.2.1      2016-12-30 CRAN (R 3.4.0)                     
 globals       0.11.0     2018-01-10 cran (@0.11.0)                     
 glue          1.2.0.9000 2018-04-11 Github (tidyverse/glue@99e0171)    
 gower         0.1.2      2017-02-23 CRAN (R 3.4.0)                     
 gtable        0.2.0      2016-02-26 CRAN (R 3.4.0)                     
 ipred       * 0.9-6      2017-03-01 CRAN (R 3.4.0)                     
 kernlab       0.9-25     2016-10-03 CRAN (R 3.4.0)                     
 knitr         1.20       2018-02-20 CRAN (R 3.4.3)                     
 lattice       0.20-35    2017-03-25 CRAN (R 3.4.3)                     
 lava          1.5.1      2017-09-27 CRAN (R 3.4.2)                     
 lazyeval      0.2.1      2017-10-29 CRAN (R 3.4.2)                     
 listenv       0.7.0      2018-01-21 cran (@0.7.0)                      
 lubridate   * 1.7.3      2018-02-27 cran (@1.7.3)                      
 magic         1.5-8      2018-01-26 cran (@1.5-8)                      
 magrittr      1.5        2014-11-22 CRAN (R 3.4.0)                     
 MASS          7.3-47     2017-02-26 CRAN (R 3.4.3)                     
 Matrix        1.2-12     2017-11-20 CRAN (R 3.4.3)                     
 MLmetrics     1.1.1      2016-05-13 CRAN (R 3.4.0)                     
 mnormt        1.5-5      2016-10-15 CRAN (R 3.4.0)                     
 munsell       0.4.3      2016-02-13 CRAN (R 3.4.0)                     
 nlme          3.1-131    2017-02-06 CRAN (R 3.4.3)                     
 nnet          7.3-12     2016-02-02 CRAN (R 3.4.3)                     
 pillar        1.2.1      2018-02-27 CRAN (R 3.4.3)                     
 pkgconfig     2.0.1      2017-03-21 CRAN (R 3.4.0)                     
 plyr          1.8.4      2016-06-08 CRAN (R 3.4.0)                     
 pROC          1.10.0     2017-06-10 CRAN (R 3.4.0)                     
 prodlim       1.6.1      2017-03-06 CRAN (R 3.4.0)                     
 psych         1.8.3.3    2018-03-30 cran (@1.8.3.3)                    
 purrr       * 0.2.4      2017-10-18 CRAN (R 3.4.2)                     
 R6            2.2.2      2017-06-17 CRAN (R 3.4.0)                     
 Rcpp          0.12.16    2018-03-13 cran (@0.12.16)                    
 RcppRoll      0.2.2      2015-04-05 CRAN (R 3.4.0)                     
 recipes       0.1.2      2018-01-11 CRAN (R 3.4.3)                     
 reshape2      1.4.3      2017-12-11 CRAN (R 3.4.3)                     
 rlang         0.2.0.9001 2018-04-14 Github (tidyverse/rlang@82b2727)   
 robustbase    0.92-8     2017-11-01 CRAN (R 3.4.2)                     
 rpart         4.1-11     2017-03-13 CRAN (R 3.4.3)                     
 rsample     * 0.0.2      2017-11-12 CRAN (R 3.4.2)                     
 scales        0.5.0      2017-08-24 CRAN (R 3.4.1)                     
 sessioninfo * 1.0.0      2017-06-21 CRAN (R 3.4.1)                     
 sfsmisc       1.1-2      2018-03-05 cran (@1.1-2)                      
 stringi       1.1.6      2017-11-17 CRAN (R 3.4.2)                     
 stringr       1.3.0      2018-02-19 CRAN (R 3.4.3)                     
 survival      2.41-3     2017-04-04 CRAN (R 3.4.3)                     
 tibble        1.4.2      2018-01-22 cran (@1.4.2)                      
 tictoc      * 1.0        2014-06-17 CRAN (R 3.4.0)                     
 tidyr       * 0.8.0      2018-01-29 cran (@0.8.0)                      
 tidyselect    0.2.4      2018-02-26 cran (@0.2.4)                      
 timeDate      3043.102   2018-02-21 cran (@3043.10)                    
 withr         2.1.2      2018-04-11 Github (r-lib/withr@79d7b0d)       
 yardstick   * 0.0.1      2017-11-12 CRAN (R 3.4.2)   
```

**Comment by DavisVaughan** [comment]
This is interesting. For reference, I am `Mac High Sierra 10.13.3` with 4 cores. I ran with `multiprocess` twice (which chooses `multicore`) and get serious throttling from `kernel_task` on the _second_ run and all runs after that until I restart R from RStudio (it looks like `kernel_task` might be spiking some the first time around as well, but its not affecting the run until the tail end).

Can you try `multisession` twice? I was able to do that and didn't see the `kernel_task` spike. 

This may also be "a thing" with High Sierra. 
https://tutorials.technology/tutorials/80-How-to-fix-kernel_task-CPU-usage-on-High-Sierra.html

**Comment by DavisVaughan** [comment]
If you want to do some other debugging / watch what `future_map` is doing, you can set `options(future.debug = TRUE)` before you run it.

**Comment by DavisVaughan** [comment]
Also, one of the main reasons for _only_ 1.77 speedup on 20 core is probably the large amount of data transfer.

Just doing:

```r
vfolds <- vfold_cv(ames_train, repeats = 1)
vfolds$bag_mod <- map(vfolds$splits, ~ bagging(Sale_Price ~ ., data = analysis(.), nbagg = 50))
x <- as.list(vfolds$bag_mod)
```

And looking at `x` in RStudio's environment pane tells me it's 667mb. Translating into 20 repeats is `667/1000 * 20` giving 13.34gb right? That could be painful to serialize/unserialize even after the run is done.

**Comment by DavisVaughan** [comment]
My guess on the `multicore` (through `multiprocess`) issue)

- You run the long running task. It runs on multiple cores. _It transfers a lot of data in the end._ For me, this is where I see the first spike in CPU usage from `kernel_task` (traced to that step using `options(future.debug=TRUE)` along with Activity Monitor), after the modeling has all been done.

**blue is essentially R, red it essentially kernel_task, the long tail is likely data transfer**

<img width="150" alt="screen shot 2018-04-16 at 9 25 58 am" src="https://user-images.githubusercontent.com/19150088/38811712-41864524-4158-11e8-87a9-0aeb208141c2.png">

- You run the long running task again, it runs on multiple cores. _Instantly_ you get a spike in CPU load from `kernel_task`. It lasts for a little while, drops off, the models run, and then it spikes up again towards the end.

<img width="150" alt="screen shot 2018-04-16 at 9 23 40 am" src="https://user-images.githubusercontent.com/19150088/38811715-44e3ccdc-4158-11e8-95d7-e720a6a1f37c.png">


My guess? Somehow the cores are not completely "cleaned up" after the first run. Watching activity monitor shows me that the 4 R processes are not there anymore, but something must be sticking around, and it likely relates to the large amounts of data being transferred. If you just return "hi" after running the models, rather than returning the large model objects, you can run the models _using multicore_ as many times as you want. This is why I have not seen this problem until now.

**Comment by topepo** [comment]
Those are all good and valid points. 

I do consistently see large speed-ups even with large transfers of data though (on this machine). [Here](http://appliedpredictivemodeling.com/blog/2018/1/17/parallel-processing) are some examples that include this machine (labeled as "2017 iMacPro (1,1) with a 3 GHz Intel Xeon W processor. There are 10 cores.") with High Sierra and >8-fold speed-ups. 

I re-ran the same file with `multisession` and `options(future.debug=TRUE)`:

```r
> plan(multisession)
> 
> tic()
> set.seed(244)
> folds <- vfold_cv(ames_train, repeats = 10) %>%
+   mutate(
+     bag_mod = future_map(splits,
+                          ~ bagging(Sale_Price ~ ., data = analysis(.), 
+                                    nbagg = 50))
+   ) 
future_lapply() ...
Finding globals ...
getGlobalsAndPackages() ...
Searching for globals ...
- globals found: [8] ‘.f’, ‘bagging’, ‘~’, ‘Sale_Price’, ‘.’, ‘analysis’, ‘sys.call’, ‘environment’
Searching for globals ... DONE
Resolving globals: FALSE
The total size of the 3 globals is 8.32 KiB (8520 bytes)
- globals: [3] ‘.f’, ‘~’, ‘.’
- packages: [2] ‘ipred’, ‘rsample’
getGlobalsAndPackages() ... DONE
 - globals found: [3] ‘.f’, ‘~’, ‘.’
 - needed namespaces: [2] ‘ipred’, ‘rsample’
Finding globals ... DONE
Getting '...' globals ...
resolve() on list ...
 recursive: 0
 length: 1
 elements: ‘...’
 length: 0 (resolved future 1)
resolve() on list ... DONE
Getting '...' globals ... DONE
Globals to be used in all futures:
Error in mutate_impl(.data, dots) : 
  Evaluation error: 'fmt' length exceeds maximal format length 8192.
```

**Comment by DavisVaughan** [comment]
Two things that can at least let you run this:

1) Apparently `sprintf` has a limit on `fmt` length causing problems with debugging output. Didn't know that.
2) That `Sale_Price ~ .` is currently going to cause problems because `future` sees it as an rlang tilde, I'll have to look into that.

Please turn this back off: `options(future.debug=FALSE)`, then you should be able to run

```r
 plan(multisession)
 
 tic()
 set.seed(244)
form <- Sale_Price ~ .
 folds <- vfold_cv(ames_train, repeats = 10) %>%
   mutate(
     bag_mod = future_map(splits,
                          ~ bagging(form, data = analysis(.), 
                                    nbagg = 50))
```

**Comment by DavisVaughan** [comment]
@topepo I went and took a look at a random one of those scripts, [this one](https://github.com/topepo/par-caret-bench/blob/master/macOS/2017%20iMacPro1%2C1%203%20GHz%20Intel%20Xeon%20W%2010core/xgb_02.R), to look at the size of the objects. 

With `len = 2` I'm getting back a 3.1 mb `mod` object. With `len = 3` I get 3.1 mb as well. Even if the len was 25 thats probably not much bigger right? At the very least, much smaller than trying to transfer 13gb around. Am I missing something?

I do agree that there is some problem with how `future` itself is dealing with the processes / data management, but I think most of the time lost is in pulling back these massive model objects from `bagging()`.

**Comment by topepo** [comment]
Okay. I put the model calculation into a function where I compute performance and got >9-fold speed-ups for both parallel executions:

```r

perf <- function(data_split) {
  mod_obj <-  bagging(Sale_Price ~ ., data = analysis(data_split), 
                      nbagg = 50)
  assess_dat <- assessment(data_split) %>%
    mutate(
      pred = predict(
        mod_obj, 
        newdata = assessment(data_split)
      )
    )
  assess_dat %>% 
    rsq(truth = Sale_Price, estimate = pred)
}

plan(sequential)

tic()
set.seed(244)
folds <- vfold_cv(ames_train, repeats = 10) %>%
  mutate(
    bagging = future_map_dbl(splits, perf)
  ) 
toc()

Sys.sleep(30)

plan(multiprocess)

tic()
set.seed(244)
folds <- vfold_cv(ames_train, repeats = 10) %>%
  mutate(
    bagging = future_map_dbl(splits, perf)
  ) 
toc()

Sys.sleep(30)

tic()
set.seed(244)
folds <- vfold_cv(ames_train, repeats = 10) %>%
  mutate(
    bagging = future_map_dbl(splits, perf)
  ) 
toc()
```

**Comment by DavisVaughan** [comment]
That's great to hear!
