### ISSUE TITLE
future_invoke_map vs invoke_map

### ISSUE THREAD

**Issue by marcosci** [DavisVaughan/furrr#30]
Hi Davis,

Maybe I am missing something obvious here, but I stumpled upon this today
while trying to parallelize my existing code:

```r
library('furrr')
library('purrr')
library('dplyr')

df <- tibble(
  f = c("runif"),
  params = list(
    list(list(10), list(10))
))

# correct return
invoke_map(df$f, flatten(df$params))

# only returns result from first list element
future_invoke_map(df$f, flatten(df$params))
```

purrr::invoke_map returns the result I would expect to so , 2x10 random numbers, whereas future_invoke_map only returns 10 numbers for the list element in the nested tibble.
A workaround is to unnest the tibble first, but as furrr usually works as a drop-in replacament this could maybe be fixed?

Cheers,
Marco

**Comment by DavisVaughan** [comment]
Totally my fault. The issue runs deeper and is in `future_map2_template()`. I'm not using the right length when creating load balanced chunks. I believe this only affects the `map2()` version and the affected line is below. I need to ensure that `n.x` becomes the max of `n.x` and `n.y` after recycling is done. 

https://github.com/DavisVaughan/furrr/blob/master/R/future_map2_template.R#L85

``` r
library('furrr')

future_map2(1, c(2, 3), ~c(.x, .y))
#> [[1]]
#> [1] 1 2
```

Thanks for pointing it out!

**Comment by DavisVaughan** [comment]
This should be fixed! Thanks for bringing it up. 

``` r
library('furrr')
#> Loading required package: future
library('purrr')
library('dplyr')
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

df <- tibble(
  f = c("runif"),
  params = list(
    list(list(10), list(10))
  ))

# correct return
set.seed(10)
invoke_map(df$f, flatten(df$params))
#> [[1]]
#>  [1] 0.50747820 0.30676851 0.42690767 0.69310208 0.08513597 0.22543662
#>  [7] 0.27453052 0.27230507 0.61582931 0.42967153
#> 
#> [[2]]
#>  [1] 0.65165567 0.56773775 0.11350898 0.59592531 0.35804998 0.42880942
#>  [7] 0.05190332 0.26417767 0.39879073 0.83613414

# only returns result from first list element
set.seed(10)
future_invoke_map(df$f, flatten(df$params))
#> [[1]]
#>  [1] 0.50747820 0.30676851 0.42690767 0.69310208 0.08513597 0.22543662
#>  [7] 0.27453052 0.27230507 0.61582931 0.42967153
#> 
#> [[2]]
#>  [1] 0.65165567 0.56773775 0.11350898 0.59592531 0.35804998 0.42880942
#>  [7] 0.05190332 0.26417767 0.39879073 0.83613414
```

Created on 2018-09-01 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).
