### ISSUE TITLE
<U+2500> appears instead of ─ with .progress = TRUE

### ISSUE THREAD

**Issue by adrfantini** [DavisVaughan/furrr#31]
On my work system, the code `<U+2500>` appears instead of `─` when using `.progress = TRUE`. This might be an issue with my shell or terminal. Maybe it would be possible to detect if this is gonna happen, and use a simpler dash instead?

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] furrr_0.1.0    future_1.7.0   pacman_0.4.6   colorout_1.1-2

loaded via a namespace (and not attached):
[1] compiler_3.4.4   magrittr_1.5     parallel_3.4.4   listenv_0.7.0    codetools_0.2-15 digest_0.6.15   
[7] globals_0.11.0   rlang_0.2.1.9000 purrr_0.2.5
```

**Comment by DavisVaughan** [comment]
Hmm, does `cli::symbol$line` give you the same issue?

**Comment by DavisVaughan** [comment]
I think i can fix this. I see what `cli` is doing now. I was not doing the right thing when I copied them. I need to essentially make the symbol switch based on whether utf8 is allowed or not.

https://github.com/r-lib/cli/blob/1ce51456bd1d8ee703e07065ccb8824862d09e73/R/onload.R#L11

**Comment by adrfantini** [comment]
Actually, `cli::symbol$line` seems to work fine...

**Comment by DavisVaughan** [comment]
Yes sorry it should actually work fine. It's smart enough to know how to switch if utf8 isn't available. I'll add that in too. That's what I was trying to say

**Comment by adrfantini** [comment]
Nice! Thanks.

**Comment by DavisVaughan** [comment]
@adrfantini can you install the dev version and see if this fixed it for you?

**Comment by adrfantini** [comment]
Sorry I'm late, I did not have access to the same machine I had this problem originally with. I can confirm the fix!
Thanks.

**Comment by amirmasoudabdol** [comment]
I can still see this issue when I'm running my code on cluster. I think this is tricker that it looks and it depends on the shell, and then emulator, distro. I think it'd be easier to just pick a simpler `-`.
