### ISSUE TITLE
Error in curl::curl_fetch_memory ?

### ISSUE THREAD

**Issue by ignacio82** [DavisVaughan/furrr#35]
I sometimes get this error when I run `furrr::future_map` . The weird thing is that i don't always get that error even if I run exactly the same script. 

```r
Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_BUFFER_TOO_SMALL (0x80090321) - The buffers supplied to a function was too small.
```

Any ideas on how to fix this? In case is relevant, I'm using `multiprocess` on Windows.

**Comment by DavisVaughan** [comment]
I won't be able to help without more information. What script are you running? What are you generally trying to do? I need a full reproducible example to be able to debug, even if it doesn't error out every time. At the very least I might have some ideas

**Comment by ignacio82** [comment]
Sadly I cannot share the data that I'm using, and I'm having troubles creating an example with fake data. Basically, I'm just using `furrr::future_map`. Sometimes I get that error, sometimes I don't.  I switched the code to use `parallel::parLapply` and everything is working smoothly.
