### ISSUE TITLE
Don't attach the future package

### ISSUE THREAD

**Issue by hadley** [DavisVaughan/furrr#40]
I think it's generally bad practice to attach other packages on load. Could you instead just re-export the handful of functions that you need from future?

**Comment by hadley** [comment]
Alternatively, you could automatically do `future::plan(multiprocess)` on load, and then I don't think there would be any general need to call future functions?

**Comment by DavisVaughan** [comment]
> Alternatively, you could automatically do future::plan(multiprocess) on load, and then I don't think there would be any general need to call future functions?

See response in #41 on this.

I mainly used a `Depend` on `future` so the user had access to every `plan()` that `future` gave them. I can re-export the core ones (`sequential`, `multicore`, `multiprocess`, `multisession`, `cluster`, `remote`) and move it to `Imports`
