### ISSUE TITLE
Feature request:  "time" progress bars

### ISSUE THREAD

**Issue by dhicks** [DavisVaughan/furrr#48]
I recently discovered `furrr`, and love how easy it is to reconfigure the parallel processing scheme as I move between my laptop and an HPC cluster.  I also really like the fact that I can use both parallel processing AND a progress bar.  I've been using `plyr`, which plays nicely with either parallel processing or a progress bar but not both.  

I would like to request more variety in the progress bars.  In particular, my preferred progress bar in `plyr` was the `'time'` bar, which included an estimate of the time until completion.  This was implemented using `plyr::progress_time()` ([link](https://github.com/hadley/plyr/blob/fe192412748d1ccb6d524caeb5bcf2b5c474fd46/R/progress-time.r)).  The successor is `dplyr::progress_estimated()` ([link](https://github.com/tidyverse/dplyr/blob/bbcfe99e29fe737d456b0d7adc33d3c445a32d9d/R/progress.R)).

**Comment by mike-lawrence** [comment]
Seconding this FR!

**Comment by DavisVaughan** [comment]
I think I'm actually going to wait until an "official" solution is supported by future. It's currently a WIP at https://github.com/HenrikBengtsson/progressr
