### ISSUE TITLE
how many cores/processes are being spawned?

### ISSUE THREAD

**Issue by randomgambit** [DavisVaughan/furrr#52]
Hello @DavisVaughan ,

Thanks for this wonderful package. I wonder if there is any way for me to set up (or monitor) how many cores or processes are used/spawned with `furrr`? I am using windows.

My usual use case is to `nest()` a tibble and to apply some function to the grouped dataframes. Hence, I mostly have embarassingly parallells problems here.

Thanks!

**Comment by randomgambit** [comment]
I see that you have a progress bar, but it seems not to work with me. Ideally, i thing it would be very useful to have something like `joblib` in python, where one can actually see the progress of each subtask. 

Something that is not entirely clear for me (and from both the documentation of `futures` and `furrr`) is whether, in windows, the RAM is shared among the different processes or not. 

Can each process access the global environment? I think not, because I need to load a dataset into the function I want to parallelize for me to make it work with `furrr`, but you know better

What do you think?
Thanks!

**Comment by DavisVaughan** [comment]
In windows, I'm pretty sure you can just look at the task manager to monitor the start up and shut down of the workers.

The progress bar is still WIP. It can definitely be better, but it's a pretty tough problem.

On Windows, you cannot access the global env of the original master process. On Mac, you can use `plan(multicore)` which forks the process in a way that you can still access global env memory.
