### ISSUE TITLE
feature request: make furrr compatible with tsibble

### ISSUE THREAD

**Issue by randomgambit** [DavisVaughan/furrr#53]
Hello

Everything is said in the title. It would be really nice that `furrr` had multiprocessing equivalents for the `tsibble` rolling functions. Have a look here https://github.com/tidyverts/tsibble/issues/66

What do you think? Is it doable?
Thanks!

**Comment by randomgambit** [comment]
@earowang

**Comment by EmilRehnberg** [comment]
@randomgambit I think this issue can be closed, right?

**Comment by randomgambit** [comment]
yes my friend
