### ISSUE TITLE
future_options(seed=) should convert integer-ish things to integer automatically

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/furrr#55]
``` r
library(furrr); future_options(seed = 123)
#> Loading required package: future
#> Error in new_future_options(globals = globals, packages = packages, seed = seed, : inherits(seed, c("logical", "integer", "list")) is not TRUE
```

Created on 2018-11-08 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by atusy** [comment]
This would help?

``` r
as_int_if_likely <- function(x) if(is.double(x) && as.integer(x) == x) as.integer(x) else x
dput(as_int_if_likely(123))
#> 123L
dput(as_int_if_likely(123L))
#> 123L
dput(as_int_if_likely(123.1))
#> 123.1
```

<sup>Created on 2019-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by GitHunter0** [comment]
> ```r
> #> Error in new_future_options(globals = globals, packages = packages, seed = seed, : inherits(seed, c("logical", "integer", "list")) is not TRUE
> ```

I'm still receiving that error message for furrr version 0.1.0

**Comment by DavisVaughan** [comment]
That’s because I haven’t sent the devel version with the fix to cran yet

**Comment by GitHunter0** [comment]
Ok, thank you @DavisVaughan
