### ISSUE TITLE
Error in plan(cluster, workers = cl) when using more than 13 workers with EC2 instance

### ISSUE THREAD

**Issue by HanjoStudy** [DavisVaughan/furrr#58]
Hi 

I am using an EC2 instance to do some basic calculations, but I am finding that as soon as I try and start more than 12 workers, the `plan(cluster, workers = cl)`  function crashes with: 
```
> plan(cluster, workers = cl)
plan(): plan_init() of ‘tweaked’, ‘cluster’, ‘multiprocess’, ‘future’, ‘function’ ...
Error in sprintf(...) : 'fmt' length exceeds maximal format length 8192
```
To reproduce the error, set `workers = rep(public_ip, times = 15L)` in `makeClusterPSOCK`:
```

options(future.debug = TRUE)

# A r3.4xlarge AWS instance
# Created from http://www.louisaslett.com/RStudio_AMI/
public_ip <- "18.206.46.236"
# This is where my pem file lives (password file to connect).
ssh_private_key_file <- "~/Desktop/programming/AWS/key-pair/dvaughan.pem"

cl <- makeClusterPSOCK(
  
  # Public IP number of EC2 instance
  workers = rep(public_ip, times = 15L),
  
  # User name (always 'ubuntu')
  user = "ubuntu",
  
  # Use private SSH key registered with AWS
  rshopts = c(
    "-o", "StrictHostKeyChecking=no",
    "-o", "IdentitiesOnly=yes",
    "-i", ssh_private_key_file
  ),
  
  # Set up .libPaths() for the 'ubuntu' user and
  # install furrr
  rscript_args = c(
    "-e", shQuote("local({p <- Sys.getenv('R_LIBS_USER'); dir.create(p, recursive = TRUE, showWarnings = FALSE); .libPaths(p)})"),
    "-e", shQuote("if (!require('furrr')) install.packages('furrr')")
  ),
  
  # Switch this to TRUE to see the code that is run on the workers without
  # making the connection
  dryrun = FALSE
)

cl

library(furrr)
plan(cluster, workers = cl)  ## error here

f <- function(x){
  x <- rnorm(x)
  return("success")
}

cars2_mod_future <- as.list(rep(1e7, 50)) %>%
  ## error here
 future_map(~f(.x))

parallel::stopCluster(cl)
```

Second error when running `future_map`:
```
future_map_*() ...
Finding globals ...
getGlobalsAndPackages() ...
Searching for globals...
- globals found: [7] ‘.f’, ‘f’, ‘{’, ‘<-’, ‘x’, ‘rnorm’, ‘return’
Searching for globals ... DONE
Resolving globals: FALSE
The total size of the 3 globals is 32.58 KiB (33360 bytes)
- globals: [3] ‘.f’, ‘f’, ‘x’
- packages: [1] ‘stats’
getGlobalsAndPackages() ... DONE
 - globals found: [3] ‘.f’, ‘f’, ‘x’
 - needed namespaces: [1] ‘stats’
Finding globals ... DONE
Getting '...' globals ...
resolve() on list ...
 recursive: 0
 length: 1
 elements: ‘...’
 length: 0 (resolved future 1)
resolve() on list ... DONE
Getting '...' globals ... DONE
Globals to be used in all futures:
Error in sprintf(...) : 'fmt' length exceeds maximal format length 8192
```

Session:

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] h2o_3.20.0.8          usethis_1.4.0         bindrcpp_0.2.2        doParallel_1.0.14     iterators_1.0.10      foreach_1.4.4         furrr_0.1.0           future_1.10.0        
 [9] glue_1.3.0            ggplot2_3.1.0         RMySQL_0.10.15        DBI_1.0.0             tidyr_0.8.2           lubridate_1.7.4       readr_1.2.1           dplyr_0.7.8          
[17] purrr_0.2.5 
```

**Comment by HanjoStudy** [comment]
As soon as I turn the `options(future.debug = FALSE)`, the error isn't there any more, but I see that some of the cores are not doing work, which is why I turned the debug on in the first place just to check if the work is being evenly distributed among the cores:
![image](https://user-images.githubusercontent.com/12710800/49229498-534f2400-f3f6-11e8-8988-e00ebe1b55b2.png)

One can also see it in the difference in runtimes between the 1 core and 15 core implementation. The 15 core `future_map` only gives us a speedup of ~4x. (If you have any other interesting benchmark scripts to force cores to work at 100% for a few minutes, let me know and I could test the job distribution in a better way) 

`future_map` with 1 core:
```
system.time(
  cars2_mod_future <- as.list(rep(1e7, 500)) %>%
    future_map(~f(.x))
)
   user  system elapsed 
  3.584   0.243 312.017 
```

`future_map` with 15 cores:
```
system.time(
  cars2_mod_future <- as.list(rep(1e7, 500)) %>%
    future_map(~f(.x))
)
   user  system elapsed 
  2.680   0.331  71.637 
```

But alas, these are just small issues. Thanks again for your work on `furrr`! Its been a game changer

**Comment by DavisVaughan** [comment]
I think you _might_ have a misunderstanding of how you should distribute over your cores on a remote worker. You will likely have to use `future_map()` twice to get this working right.

Generally, you call `future_map()` once and that shards the data over multiple workers (multiple EC2 instances!).

Then you call `future_map()` again inside that first call, and that will go in parallel _on each instance_.

So since you seem to have 1 instance, you would probably call `future_map` once with some kind of dummy variable just to get your data on the instance, then call it again to do the real work. 

This is a tricky idea, but I've tried to document it in the last example on this gist
https://gist.github.com/DavisVaughan/865d95cf0101c24df27b37f4047dd2e5#gistcomment-2606332

really read through that and try to understand what is happening and hopefully you can figure it out

**Comment by DavisVaughan** [comment]
one key point is that i dont think you need `rep(public_ip, times = 15L)` it should just be `public_ip`. again, see the gist!
