### ISSUE TITLE
is dynamic task allocation across workers possible?

### ISSUE THREAD

**Issue by sheffe** [DavisVaughan/furrr#59]
(I tried to frame these questions generally, but if it shades too far to advice on an idiosyncratic application, feel free to close!)

I'm running a fairly large bootstrap routine through `furrr::future_pmap` and `plan(multiprocess)` right now. It's running on an m4.16xlarge EC2 instance (64 core/256 GB RAM) and going slower than I anticipated. I think I see what's happening, but wanted to ask about the *intended* behavior first.

I can watch `htop` along the way. I see all available cores busy when I start the job, as expected, but typically by ~75% of expected elapsed runtime I see the number of cores in active use decline steadily. The last few minutes of a run are typically occupied by just a few working cores. I'm back-enveloping that decline as worth perhaps 20-25% of total runtime.

I assume what's happening is that work is divided across cores at the outset, and there's enough variance in the runtime of my function calls that some cores can finish their work faster than others. 
1. Is that assumption true?
2. Is there an option for dynamic task allocation, within furrr itself or future?
3. If there's no possibility of dynamic allocation, are there any general good practices to claw back some of that runtime?

So far, I've just tried minimizing the memory footprint and runtime variance for these function calls. It's timing in the range of 400-600ms per call, median at 465ms. The memory management overhead isn't too bad -- no large globals being copied, everything inside the call is vectorized carefully, and the returned result is a numeric matrix of just 40 elements. The machine never exceeds 60GB of RAM (25% of total) even at the largest jobs.

I've also hit this in very different contexts, e.g. webscraping through a proxy that enables parallel hits, where the function call runtime variance is much higher. In that case, I found it more efficient to write out logs, stop the job, extract from logs whatever didn't finish, and reallocate the work in a new future_map call. (That doesn't seem like it's a good practice, but in a pinch....)

(A more general observation. I'm running a 1M-replicate bootstrap over 1M individual raster cells and repeating that for ~3,000 rasters, all in R, all in about 200 lines of code. I am *so* happy with this package. `furrr` has cut the time between testing a function and scaling it to absurd levels down to basically 0. Thank you!)

**Comment by DavisVaughan** [comment]
Hi @sheffe, thanks for the nice words about furrr. I have an answer for you that is hopefully satisfying, but requires a bit more work on your part.

> I assume what's happening is that work is divided across cores at the outset, and there's enough variance in the runtime of my function calls that some cores can finish their work faster than others.

This is correct! For better or worse, furrr evenly slices up your job into chunks that it can ship off to each core you have available.

> Is there an option for dynamic task allocation, within furrr itself or future?

Not within furrr currently, but within future....see the comment below.

**Comment by DavisVaughan** [comment]
``` r
library(furrr)
library(rsample)
library(listenv)
library(tictoc)

# ..............................................................................

# 16 bootstraps
n <- 16

# The ones at the end take much longer than
# the ones at the beginning
straps <- bootstraps(iris, times = n)
delays <- seq_len(n)

# Each bootstrap takes a varying amount of time
process_strap <- function(split, delay) {
  Sys.sleep(delay)
  nrow(analysis(split))
}

# ..............................................................................

# Sends bootstraps 1-8 to the 8 cores immediately, with no hanging of the console.
# Then, once the request for the 9th bootstrap to be sent to a worker is made,
# it waits for the next core to be available, and once one is open, it sends
# it along. Continue this for all bootstraps

# This has better performance, and the time on each core will probably
# be something like:
# Core 1) 1 sec + 9  sec 
# Core 2) 2 sec + 10 sec 
# Core 3) 3 sec + 11 sec
# Core 4) 4 sec + 12 sec
# Core 5) 5 sec + 13 sec
# Core 6) 6 sec + 14 sec
# Core 7) 7 sec + 15 sec
# Core 8) 8 sec + 16 sec

# So the total time is the longest spent on any core, or around 8 + 16 = 24 sec

plan(multiprocess, workers = 8)

vals <- listenv()

# dynamic allocation
tic()
for(i in seq_len(nrow(straps))) {
  
  strap <- straps[i,]
  delay <- delays[i]
  
  vals[[i]] %<-% process_strap(strap$splits[[1]], delay)
  
}
vals <- as.list(vals)
toc()
#> 25.492 sec elapsed

# ..............................................................................

# This evenly divides your 16 splits into 8 groups of 2 (in order)
# Then it sends all 8 groups off to the 8 cores all at once
# So core 1 has bootstraps [1,2] (which take 1 and 2 seconds respectively)
# So core 8 has bootstraps [15,16] (which take 15 and 16 seconds respectively)

# So here you are limited by the 8th core
# and you get ~15 + 16 = 31 seconds

# reset
plan(multiprocess, workers = 8)

# batch allocation
tic()
vals2 <- future_map2(straps$splits, delays, process_strap)
toc()
#> 31.167 sec elapsed
```

<sup>Created on 2019-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by sheffe** [comment]
Thank you @DavisVaughan! That is exactly what I needed -- pretty certain that this solution will speed up half of my current projects. I'd also never seen the `tictoc` package before -- very slick.

(This was a way-past-expectations thorough response -- really appreciate it. If someone from my team tries to buy you a beer at rstudio::conf next week, you'll know why...)

**Comment by sheffe** [comment]
@DavisVaughan a followup thought here -- I implemented your solution last night and it's going beautifully, with some other lessons learned. Maybe worth a docs PR if I can consolidate this well -- LMK.

I'm seeing a pretty strong performance relationship between `future_options(scheduling = N))` and the expected runtime variance of the function being iterated. 
- If `scheduling = N` goes too high, there's more overhead burned in division/allocation of jobs, and it may not compensate well for the runtime hit. (For the task that prompted my question, testing `scheduling = Inf` was a pretty severe performance reduction -- hundreds of thousands of highly optimized function calls that can't directly be vectorized, so nearly all of the time went to dividing up and managing the returned futures. The 64 cores were largely not used compared to the overhead, for that specific problem. For web scraping, parallel file reads on very different file sizes, etc -- long-running functions especially -- that probably inverts.) 
- `scheduling = 200` brought it closer to `scheduling = 1`
- For now, the 25-50 range is where I'm seeing some nice improvement. 

Before this issue, I'd been watching cores finish ~25% before others at most with `scheduling = 1`, so I'm guessing that this is the sweet spot for minimizing work allocation overhead while still dividing work into small enough chunks that we bring the "core disuse from early finishing" range from a max of 25% down to a max of ~2-4%.

I think there's a way to test that hypothesis directly, and at least demonstrate how to figure it out for a specific problem in a vignette perhaps.

This issue probably doesn't need reopening. If I have any luck with turning that profiling into reliable heuristics, I'll report back. I'm still completely incredulous that this worked so well with such a small change to the code. Thanks again!

**Comment by DavisVaughan** [comment]
I think this works best when you have, say, 50 models to run, and 10 cores and each model takes a varying amount of time to finish, but each one takes at least a few minutes or so to run. That way the overhead is more in the task than in the allocation of data.

That's good rationale for why the default is `1`, more intricate tuning requires some domain knowledge of your exact problem.

I'm happy it seems to be helping though!
