### ISSUE TITLE
Limit Cores

### ISSUE THREAD

**Issue by alexhallam** [DavisVaughan/furrr#60]
I share a VM and need to limit the cores that `furrr` uses. I was thinking that an option for this functionality would exist in `future_options()`,  but I did not see anything about limiting cores.  Can a parameter for the number or percent of cores to use be passed to `furrr`? If not could this be a feature request?

**Comment by DavisVaughan** [comment]
its a future thing, not a furrr thing! `plan(multiprocess, workers = 4)` for example.

To limit a percentage of available cores, see the very bottom of this vignette
https://cran.r-project.org/web/packages/future/vignettes/future-3-topologies.html
