### ISSUE TITLE
resetting nms in multi_resolve when a subset of jobs fail

### ISSUE THREAD

**Issue by yonicd** [DavisVaughan/furrr#64]
when jobs fail the size of the vector mismatches the length of `nms` in `multi_resolve` causing the wrap up to fail.

would it be possible to reset `nms` if the lengths mismatch to allow for the successful jobs to be returned?

https://github.com/DavisVaughan/furrr/blob/b4ad6addda5cb2fab4baf51434bdacf7a75a94ad/R/resolve.R#L18

**Comment by DavisVaughan** [comment]
It might be easier to actually return something sensible on failure so values has the same length as nms. Do you have an example for me to test with?

**Comment by DavisVaughan** [comment]
I'm not entirely sure how to reproduce an example of a remote worker crashing, but I can crash a local multisession worker with `library(trump)`. It seems like future will error when a worker crashes completely.

I think in the future there will be a future API for restarts, but until then I'm not sure there is much I can do

``` r
library(furrr)
#> Loading required package: future
#> Warning: package 'future' was built under R version 4.0.2

plan(multisession, workers = 2)

future_map(1:5, ~{
  if (.x == 1L) {
    library(trump) # <- will crash the worker
  } else {
    .x
  }
})
#> Error in unserialize(node$con): Failed to retrieve the value of MultisessionFuture (<none>) from cluster RichSOCKnode #1 (PID 73952 on localhost 'localhost'). The reason reported was 'error reading from connection'. Post-mortem diagnostic: No process exists with this PID, i.e. the localhost worker is no longer alive.

plan(sequential)
```

<sup>Created on 2020-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yonicd** [comment]
Yeah. I think the main problem was with remote vs multisession workers was that in remote workers the user could benefit from retrieving results from the non-crashed workers (usually due to swamping the memory of one of the worker machines) as compared to the multisession where it is the same machine (at least in your example). In the former it is annoying to lose all the results from stable machines just because one machine is problematic. if that makes sense
