### ISSUE TITLE
Fault tolerant behavior when a worker crashes

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/furrr#65]
If you have 4 workers, each with 10 things to run, and one of those workers completely crashes, then you still might want the 30 things that succeeded. Right now, this doesn't seem to work because of the behavior of `multi_resolve()` (it seems like the names of `x` are added to `values` which might not be the same length of x if something crashed).

If a worker has crashed, we should just `NULL` for each element that was sent to that worker. That way, when we add names to `values` in `multi_resolve()`, it is the same length as `x`.

**Comment by DavisVaughan** [comment]
This line might return something where if you `fold()` it, the result is not equal to the original length of `x`.
https://github.com/DavisVaughan/furrr/blob/master/R/resolve.R#L8

here is where an error is thrown
https://github.com/DavisVaughan/furrr/blob/master/R/resolve.R#L18

As seen in #64

**Comment by para2x** [comment]
Does anybody know if there has been any progress on this issue ?
I'm getting this error as a result of this issue :
```
Error in names(values) <- nms : 
  'names' attribute [15] must be the same length as the vector [3]
Calls: sda.enkf.multisite ... <Anonymous> -> future_map_template -> multi_resolve
```

**Comment by DavisVaughan** [comment]
I don't think this generalizes well to the atomic case. Say you call `future_map_dbl(1:6)` and `3:4` fails on the worker. Would you just put `NA_real_` values in slots 3 and 4 of the output? With a warning maybe? That seems worse than an error because it could be very surprising
