### ISSUE TITLE
`future_map` only returns calls to `print` / `warning` / etc after the end of the entire task

### ISSUE THREAD

**Issue by wjchulme** [DavisVaughan/furrr#67]
Unlike `map`, `future_map` (+ sister functions) doesn't print objects at the time that `print(object)` is called. Instead it prints everything at the end of the `future_map` call. Example:

    print.sleep <- function(x){
      print(x)
      Sys.sleep(1)
      print(toupper(x))
      Sys.sleep(1)
    }
    
    purrr::map(letters[1:3], print.sleep)

    furrr::future_map(letters[1:3], print.sleep)

The first prints as soon as `print(x)` is called and will return as 

    [1] "a"
    #(delay)
    [1] "A"
    #(delay)
    [1] "b"
    #(delay)
    [1] "B"
    #(delay)
    [1] "c"
    #(delay)
    [1] "C"

The second prints only after all calls are evaluated, and will return the printed objects all at once at the end. 

    [1] "a"
    [1] "A"
    [1] "b"
    [1] "B"
    [1] "c"
    [1] "C"

This is sensible behaviour - if multiple functions are running in parallel then there may be multiple prints that will conflict and it could get messy. In the example above it might print something like

    [1] "a"
    #(delay)
    [1] "b"
    #(delay)
    [1] "A"
    #(delay)
    [1] "c"
    #(delay)
    [1] "B"
    #(delay)
    [1] "C"

if each process starts at slightly different times. 

But is it possible to print as soon as each parallelised function is resolved? Rather than only printing everything at once at the end. This would guarentee that all printed objects / warnings from the same function call would stay together and avoid prints from different functions being jumbled up.

This would help for example to keep track of any warnings returned before the process has finished running, and terminate early if necessary. 

I appreciate there's an issue with the order in which parallel processes are resolved (so it might output "a A / c C / b B") but this could be clarified by also returning the index of the process: "1: a A / 3: c C / 2: b B" either manually in the parallelised function itself, or automatically with an inbuilt `future_map` argument.

**Comment by DavisVaughan** [comment]
This is something that I believe is being worked on in the future package which is what furrr is built on. I think what will happen is that as soon as an individual future is ready, it will be able to print all of the output for that future. It will always maintain the order in which the futures were created. So what might happen with that is:

```
# future 1 finishes, print everything
[1] "a"
[1] "A"
#(delay)
# future 2 finishes, print everything
[1] "b"
[1] "B"
#(delay)
# future 3 finishes, print everything
[1] "c"
[1] "C"
```

Nevertheless, it isn't something ill be able to control from furrr, so im going to close

**Comment by georgevbsantiago** [comment]
One question:

With the current version 1.21.0 [2020-12-09] of the future package, would it be possible to implement an argument that allows printing "in real time" ?. With one result:

```
[1] "a"
#(delay)
[1] "b"
#(delay)
[1] "A"
#(delay)
[1] "c"
#(delay)
[1] "B"
#(delay)
[1] "C"
```

This functionality would be very useful for monitoring the execution of Web Scraping with `furrr::future_walk`.
