### ISSUE TITLE
Does furrr always return results in the same order as the list/data provided?

### ISSUE THREAD

**Issue by warkentinmatt** [DavisVaughan/furrr#68]
I think the question is pretty straightforward, and through my cursory testing it seems to be true that `furrr` functions like `future_map` and other implementations (i.e. `future_map2`, `future_pmap`, etc.) will always return the results of a function call into a list (or other specified vector format) in the order of the list/data provided, even if some function calls for some list-items takes much longer/shorter to run.

Is this definitively true? I suspect it is, but am hoping for confirmation from the package dev directly.

Also, as far as determining which jobs are shipped together, it seems to me that if, lets say, you had a 4 core processor and 8 jobs (function calls) that jobs 1 & 5 would go together, jobs 2 & 6, and so on. Is this a correct understanding of how the parallel jobs are distributed to the cores?

Thank you in advance for your help.

**Comment by Deleetdk** [comment]
I had the same worry, and did some testing, and yes, seems true. Here's a simple test:

```
library(furrr)

#activate parallel
plan(multiprocess)

#sleep random amount of time in each thread
future_map_dbl(1:8, function(x) {
  Sys.sleep(runif(1))
  x
})
```

This always returns the vector 1:8 as intended despite these processes taking different amounts of time so the returning order would be different.

**Comment by DavisVaughan** [comment]
Yes it should always come back in the order provided!

Regarding how the jobs are shipped, this is somewhat controlled by the "scheduling" option in `future_options()`.

**Comment by warkentinmatt** [comment]
Thanks @Deleetdk and @DavisVaughan for your replies.
