### ISSUE TITLE
“fold” not available!

### ISSUE THREAD

**Issue by skalyan91** [DavisVaughan/furrr#70]
I’m trying to multiply a list of matrices together, and would like to be able to use `fold` instead of `purrr::reduce`. However, when I try to use `furrr::fold`, I get the error `'fold' is not an exported object from 'namespace:furrr'`!

The help file for `fold` also claims that the function is from the `future.apply` package; but I’m not able to find this function anywhere in the documentation for that package.

If `fold` isn’t available, it probably shouldn’t be in the documentation. (And yet, the function definition is right there in this GitHub repo!)

**Comment by skalyan91** [comment]
I just tried installing `furrr` from the GitHub repo, in case this issue is specific to the version on CRAN—but I’m still not able to use the `fold` function (I’m getting the same error).

**Comment by DavisVaughan** [comment]
fold() is an internal function, documented so I remember what it does. But the documentation does need a `@keyword internal` tag so it doesn't show up as easily

**Comment by skalyan91** [comment]
OK. May I ask why it’s an internal function? I think a parallelised version of `reduce()` would be really useful for an end-user!

**Comment by DavisVaughan** [comment]
It's not in parallel! It's just more memory efficient than the base function. If you really want it, I would just copy it out of furrr for your own use. It doesn't really fit the API here
