### ISSUE TITLE
Setting options() in workers

### ISSUE THREAD

**Issue by datawookie** [DavisVaughan/furrr#77]
Hi,

Firstly, thanks for `furrr`: it's a complete game changer!

I've been trying to use `future_map2()` over a function which is submitting requests to a (local) OSRM server.

At the top of my script I have the following:

```
library(furrr)
plan(multiprocess)

library(osrm)
options(osrm.server = "http://127.0.0.1:5000/")
```

Here the call to `options()` is ensuring that the OSRM requests go to the local server. However it seems that inside `future_map2()` these options are not propagated to the workers, with the result that the requests are going to the public OSRM server... which is taking massively longer, completely defeating the objective of running the requests in parallel.

The weird thing is that I haven't run this script in a while and I'm almost 100% certain that the last time I did run it this all worked.

Anyway, I was just wondering whether there is some special incantation that I can use to get this option to apply to the workers?

Thanks a lot!

Best regards,
Andrew.

**Comment by datawookie** [comment]
Hi @DavisVaughan, just been chatting to a colleague who suggested setting these options *inside* the function which I'm running in parallel. That seems like a good option to me. Are there better alternatives? Thanks, Andrew.

**Comment by Ax3man** [comment]
This is a `future` issue: https://github.com/HenrikBengtsson/future/issues/134

**Comment by Ax3man** [comment]
also answered already here: https://github.com/DavisVaughan/furrr/issues/36

**Comment by datawookie** [comment]
Thanks. Helpful link!
