### ISSUE TITLE
Use option object

### ISSUE THREAD

**Issue by hadley** [DavisVaughan/furrr#8]
Rather than including `future.globals = TRUE, future.packages = NULL, future.seed = FALSE, future.lazy = FALSE, future.scheduling = 1.0` in the arguments for every function, I think it would be cleaner to create an "option" object:

```R
future_opts <- function(future.globals = TRUE, future.packages = NULL, future.seed = FALSE, future.lazy = FALSE, future.scheduling = 1.0) {
  
}
```

Then each function would only need a single argument, and it will be much to add options in the future.

**Comment by DavisVaughan** [comment]
Definitely. I'm planning on cleaning that up in the next few days. It was getting to be a hassle. This is a nice way to do so. Thanks!

**Comment by DavisVaughan** [comment]
@hadley, I've updated `furrr` to include `future_options()` to build a set of options. This greatly streamlined the interface (and the docs) as we now have:

```r
future_map(.x, .f, ..., .progress = FALSE, .options = future_options())
```

Thanks for the advice!

Here are a few examples of the interface in practice:

``` r
library(furrr)
#> Loading required package: future

plan(multisession)
```

``` r
#### Selective exporting of variables

# Export only x
x <- 1
y <- 1

future_map(1, ~x) # black magic
#> [[1]]
#> [1] 1

future_map(1, ~x, .options = future_options(globals = "y")) # no magic
#> Error in ...future.f(...future.x_jj, ...): object 'x' not found

future_map(1, ~x, .options = future_options(globals = "x")) # no magic
#> [[1]]
#> [1] 1
```

``` r
#### Selective exporting of packages

future_map(1, ~tibble(x = 1), .options = future_options(packages = "tibble")) # no magic
#> [[1]]
#> # A tibble: 1 x 1
#>       x
#>   <dbl>
#> 1     1

library(tibble)
future_map(1, ~tibble(x = 1)) # magic
#> [[1]]
#> # A tibble: 1 x 1
#>       x
#>   <dbl>
#> 1     1
```

Created on 2018-05-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
