### ISSUE TITLE
migration from multidplyr's partition() to furrr's future_map()

### ISSUE THREAD

**Issue by julou** [DavisVaughan/furrr#80]
Hi,

I suspect that this is more a support request than a bug report :)

I want to compute several linear models for a large number of short time series, i.e. `y1~x`, `y2~x`, `log(y1)~x`, etc for thousands of time series with 20-50 points.
So far I've relied on multidplyr and I'm now refactoring to use furrr.

Here is a reprex using a dummy repetition of `mtcars`:

```r
library(tidyverse)
library(RcppArmadillo)
library(future)
library(furrr)
plan(multisession, workers=4)

# n <- 1e4
n <- 1e2
mydata <- tibble(idx=1:n, data=list(mtcars))

mydata %>%
  mutate(
    computed = future_map(data, ~ {
      mod1 <- lm(log(wt)~mpg, .)
      mod2 <- fastLmPure( cbind(1, .$mpg), log(.$wt) )
      mod3 <- fastLmPure( cbind(1, .$mpg), log(.$wt) )
      mod4 <- fastLmPure( cbind(1, .$mpg), log(.$wt) )
      tibble(
        s1 = mod1$coefficients[2], s1se=summary(mod1)$coefficients[2,2],
        s2 = mod2$coefficients[2], s2se=mod2$stderr[2],
        s3 = mod3$coefficients[2], s3se=mod3$stderr[2],
        s4 = mod4$coefficients[2], s4se=mod4$stderr[2],
      )
    }, .progress = TRUE, .options=future_options(scheduling=1) ), 
  ) %>%
  unnest(computed)
```

I wrote it this way (instead of calling `future_map()` once per model and storing each model as a list-column) because I was worried that the data of each time series would have to be passed between cpus every time I would call `future_map()`. Is this correct?

I've now spent quite a lot of time playing with options, number of workers, etc and I don't understand why I dont gain much time when I use larger numbers of workers. My understanding is that `scheduling=1` means that data will be split in as many shards as there are workers in the current plan. However, if I systematically vary the number of workers, I don't get the performance boost that I get with functions taking longer:

```r
test <- function(.n=0, ...) {
  if (.n==0) {
    plan(sequential)
  } else {
    plan(multisession, workers=.n)
  }
  
  tic()
  mydata %>%
    mutate(
      computed = future_map(data, ~ {
        mod1 <- lm(log(wt)~mpg, .)
        mod2 <- fastLmPure( cbind(1, .$mpg), log(.$wt) )
        mod3 <- fastLmPure( cbind(1, .$mpg), log(.$wt) )
        mod4 <- fastLmPure( cbind(1, .$mpg), log(.$wt) )
        tibble(
          s1 = mod1$coefficients[2], s1se=summary(mod1)$coefficients[2,2],
          s2 = mod2$coefficients[2], s2se=mod2$stderr[2],
          s3 = mod3$coefficients[2], s3se=mod3$stderr[2],
          s4 = mod4$coefficients[2], s4se=mod4$stderr[2],
        )
      }, ... ), 
    )
  .ts <- toc(quiet=TRUE)
  return(sprintf('using %d worker(s): %s', .n, toc.outmsg(.ts[[1]], .ts[[2]], NULL)))
}

runs <- map(0:8, test)
```

```
with n = 1e4
using 0 worker(s): 13.916 sec elapsed
using 1 worker(s): 14.43 sec elapsed
using 2 worker(s): 9.728 sec elapsed
using 3 worker(s): 8.515 sec elapsed
using 4 worker(s): 7.963 sec elapsed
using 5 worker(s): 7.975 sec elapsed
using 6 worker(s): 8.356 sec elapsed
using 7 worker(s): 9.145 sec elapsed
using 8 worker(s): 19.717 sec elapsed

NB: using purr's map(), it takes 13-15sec as expected
```

I suspect that I'm spreading the task across cpus in a way that I have an unnecessarily large overhead. Monitoring cpus activity, I noticed that I never have more than 2-4 active at a given time when running this example, even when the number of workers is > 4. I would really appreciate any advice on how to use future_map() better in this context. I care much in this case since I will ultimately run my code on a server node where I can use 30-50 cpus at the same time so it doesn't make sense to launch all these workers and have only a few of them running (in my current tests, also 2 to 4).

Thank you very much.

**Comment by julou** [comment]
here is my laptop setup:

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tictoc_1.0                RcppArmadillo_0.9.300.2.0 pryr_0.1.4               
 [4] furrr_0.1.0               future_1.12.0             forcats_0.4.0            
 [7] stringr_1.4.0             dplyr_0.8.0.1             purrr_0.3.2              
[10] readr_1.3.1               tidyr_0.8.3               tibble_2.1.1             
[13] ggplot2_3.1.1             tidyverse_1.2.1          

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1           cellranger_1.1.0     pillar_1.3.1         compiler_3.5.3      
 [5] plyr_1.8.4           tools_3.5.3          digest_0.6.18        jsonlite_1.6        
 [9] lubridate_1.7.4      gtable_0.3.0         nlme_3.1-137         lattice_0.20-38     
[13] pkgconfig_2.0.2      rlang_0.3.4          cli_1.1.0            rstudioapi_0.10     
[17] microbenchmark_1.4-6 parallel_3.5.3       haven_2.1.0          withr_2.1.2         
[21] xml2_1.2.0           httr_1.4.0           globals_0.12.4       generics_0.0.2      
[25] hms_0.4.2            grid_3.5.3           tidyselect_0.2.5     glue_1.3.1          
[29] listenv_0.7.0        R6_2.4.0             fansi_0.4.0          readxl_1.3.1        
[33] modelr_0.1.4         magrittr_1.5         codetools_0.2-16     backports_1.1.4     
[37] scales_1.0.0         rvest_0.3.3          assertthat_0.2.1     colorspace_1.4-1    
[41] utf8_1.1.4           stringi_1.4.3        lazyeval_0.2.2       munsell_0.5.0       
[45] broom_0.5.2          crayon_1.3.4        
```

**Comment by DavisVaughan** [comment]
> I wrote it this way (instead of calling future_map() once per model and storing each model as a list-column) because I was worried that the data of each time series would have to be passed between cpus every time I would call future_map(). Is this correct?

This is correct


For your other issues, I think the main problem is that the linear models are all finishing too quickly for you to get any real performance boost. Essentially the time is spent shuffling lots of small datasets around, and the actual computation on each worker is very quick. furrr works best when the work you are doing on each worker takes a long time. The best thing you can do here is probably cut it over 2-3 workers so you only send a few large chunks of data over.

**Comment by julou** [comment]
Thank you very much for your reply. 

Is there a way to use only k workers of a current plan having n?

Also I guess I'm puzzled because I'm refactoring code of the style

```r 
mydata %>% 
  group_by(var1, var2) %>% 
  partition() %>% 
  do((function(.df) {
    return(tibble(...))
  })(.)) %>% 
  collect()
```

 to 

```r 
mydata %>% 
  group_by(var1, var2) %>% 
  nest() %>% 
  mutate(computed=future_map(data, ~ {
    return(tibble(...))
  }, .progress=TRUE)) %>% 
  unnest(computed)
```

My naive expectation would be that the overhead should be similar. But for the moment it seems like multidplyr's partition() was scaling up much nicer. Of course I know nothing about the internals, so my (again naive) preconception was that setting up a worker should take some overhead, but I somehow didn't expect it to scale so strongly with how much data you feed it (as long one talks 10s or 100s of MB not of GB). Given that my example is already taking 10s of seconds, I would expect using 4 or 40 workers to make an almost 10x difference. But I dont see that.
This all makes me feel a bit nostalgic of course… And willing to improve my future_map syntax :)

Any other hint will be highly appreciated! In particular could you maybe comment on why I never see more than a few cpus busy at a given time. To me this suggests that the data is not passed in one go. But you wrote that it is! Or that I really overlook something.

**Comment by julou** [comment]
Also I renamed the topic (assuming that a few others might have to migrate one; but I realise that multidplyr's user base is tiny).

Another issue I'm now running into seems to come from the fact that most of my code is in .Rmd files that I render from a project main .R script, hence making sure that their evaluation takes place in the global environment. (I find this a convenient way to split my analysis into coherent parts which of course has e a chronological dependence i.e. part2.Rmd can only be rendered after part1.Rmd since some variables are created in the latter). Some larger code chunks involving future_map() are computed fine when I interactively run them. But if I render the .Rmd file they are in, the corresponding chunk takes forever and I see that only the rsession process is busy, none of the R processes of the workers.

Is it by design? am I overlooking something here as well?

**Comment by stemangiola** [comment]
> My naive expectation would be that the overhead should be similar. But for the moment it seems like multidplyr's partition() was scaling up much nicer.

If I can add my experience; as much as I like future_map, I also get much better core utilization with multidlyr (doing manual partitioning = number of cores), for all problems tried so far.

**Comment by DavisVaughan** [comment]
I really think that for these short tasks, most of the time was spent shuffling data around between workers. That is what a little profiling is telling me, at least. I don't think there is anything actionable to do here.
