### ISSUE TITLE
using .progress = T with plan(remote) fails

### ISSUE THREAD

**Issue by jzadra** [DavisVaughan/furrr#81]
When using .progress = T with future_map, if the `plan(remote)` is set, it fails with a temp directory error.

```
plan(remote, workers = "remote server here")
mtcars %>% 
group_split(cyl) %>% 
future_map(~.x %>% mutate(mpgx2 = mpg * 2), .progress = T)
```

Error in file(temp_file, "a") : cannot open the connection
In addition: Warning message:
In file(temp_file, "a") :
  cannot open file '/var/folders/5_/l71sk6kn29z17n011g8kld5m0000gp/T//Rtmp5g8ejR/file2a622cea910f.txt': No such file or directory

**Comment by DavisVaughan** [comment]
`.progress` will not work for any plan that is remote. It only works for local plans like mulicore/multisession/multiprocess.

The docs should probably be more clear about this, and to prevent the error we should try and detect the plan type and set `.progress = FALSE` if it won't be useful
