### ISSUE TITLE
future_walk() does not mimic walk() behaviour while using assign()

### ISSUE THREAD

**Issue by MokeEire** [DavisVaughan/furrr#83]
I am trying to assign each excel sheet in a workbook to its own individual dataframe.  I can do this using purrr's `walk()` with the following code:

    walk(excel_sheets(file), 
            function(x) assign(tolower(str_replace_all(x, " ", "_")), 
                               read_xlsx(here(file), sheet = x), 
                               # Assign in global environment
                               envir = .GlobalEnv))

However when I substitute `future_walk()` for `walk()`, the assignment does not occur.

**Comment by DavisVaughan** [comment]
This will not be possible! If you use `future_walk()` then you are reading the excel files into _totally different R sessions_. So you are assigning the results into the global env in those r sessions, not your master r session. Then when `future_walk()` ends, those sessions are shut down / cleaned up so the results disappear. You should probably just use `future_map()` if you really want to do this, and don't use `assign()`.

**Comment by MokeEire** [comment]
Thanks for the explanation!  I had a feeling I was misusing the function.
