### ISSUE TITLE
Straggler processes (sched_yield = 0)

### ISSUE THREAD

**Issue by philerooski** [DavisVaughan/furrr#84]
On multiple occasions, I've had furrr child processes take much longer to exit than expected. In all cases I had to kill the child process before it exited by itself.

If I spy on the child process using `strace` all I see is
```
sched_yield()                           = 0
```
outputted over and over again. In some cases there is only one child process straggler. In the most recent case, there are two. According to `top`, each process is occupying 100% CPU, but after days of running at this level (and the dozens of other processes already having completed their tasks successfully) the two processes still haven't successfully exited.

Progress is stuck near 100%
```
Progress: ───────────────────────────────────────────────────────────────  100%
```

Here is an outline of my code:
```
plan(multiprocess)
features <- furrr::future_pmap_dfr(input_dataframe, mapping_function, .progress = TRUE)
```
This is being run on Amazon Linux.

Applying `mapping_function` to a single row of the `input_dataframe` should only take a few minutes to execute, so unless these processes were given an inordinate amount of rows to process relative to the other, already exited processes I believe they should have exited by now.

Please let me know if any of this is expected behavior or if there is additional information I can provide.

**Comment by philerooski** [comment]
Possibly related to #59

**Comment by EmilRehnberg** [comment]
@philerooski I'm having similar issues (I don't know how to check the processes like you did though).
Did you find a solution to this?

**Comment by philerooski** [comment]
I did not. I ended up caching the results of the mapping function to disk and implementing a diff operation so that I can kill and restart my script as needed and begin where I left off. It was a lot of mess that I hoped to avoid by using this package but... what can you do 🤷‍♂ 

What may help you is using the `scheduling` parameter with `future_options`:
```
future_map2(straps$splits, delays, process_strap, 
                     .options = future_options(scheduling = Inf))
```

From my (rough) understanding, `scheduling` is 1 by default, so that if `n` jobs are being split across `k` processes, each process will be given `n/k` jobs exactly once. But if one of the processes hangs, you lose somewhere between 1 and `n/k` results (assuming you're caching your results -- if you're not caching your results you lose all `n` results). If you set `scheduling` to `Inf`, each process will only be given 1 job at a time, so that if that process hangs, the scheduler can give those other `n/k - 1` jobs to other, non-busy processes. This incurs additional overhead, but that overhead is relatively small if you have long running jobs.

See #59 for a more fleshed out explanation.

**Comment by DavisVaughan** [comment]
I'm sorry that the hangs are happening, unfortunately I'm not entirely sure what can be done here to prevent the issues you are having. Setting `scheduling = Inf` plus some caching thing sounds awful, I'm sorry you had to do that, but it does sound like a reasonable work around to ensure that you can keep some of the results.

**Comment by philerooski** [comment]
@DavisVaughan I'm not familiar enough with the programming to suggest any solution either. Thanks for following up!
