### ISSUE TITLE
furrr no longer working in rstudio? multisession multiprocess

### ISSUE THREAD

**Issue by picousse** [DavisVaughan/furrr#87]
Hi,
I'm working a lot with furrr inside Rstudio.

```
plan(multiprocess)
```

However this is now kicked by rstudio (because of stability reasons?

the error I now get is:

```
[ONE-TIME WARNING] Forked processing ('multicore') is disabled in future (>= 1.13.0) when running R from RStudio, because it is considered unstable. Because of this, plan("multicore") will fall back to plan("sequential"), and plan("multiprocess") will fall back to plan("multisession") - not plan("multicore") as in the past. For more details, how to control forked processing or not, and how to silence this warning in future R sessions, see ?future::supportsMulticore
```

when switching to 
```
plan(multisession)
```
a whole lot of things no longer work.

Any clue how to fix this?

**Comment by grantmcdermott** [comment]
See: https://github.com/HenrikBengtsson/future/issues/299

Q: Why are you manually switching to `plan(multisession)` after future automatically reverts to that state when `plan(multiprocess)` is called within RStudio (as detailed by the warning message)? If you just try to run your code with the usual `plan(multiprocess)` &mdash; ignoring the warnings &mdash; do you still run into problems?

More generally, it's hard to offer debugging help without more information or specific examples. What exactly does "a whole lot of things" refer too? You should really consider providing a reprex; see [here](https://reprex.tidyverse.org/). Your `sessionInfo()` output would be helpful too.

**Comment by DavisVaughan** [comment]
> a whole lot of things no longer work

`plan(multisession)` should still work fine. If it doesn't, you might have been making unsafe assumptions that only held true in a forked environment
