### ISSUE TITLE
.progress not working inside mutate for nested list columns 

### ISSUE THREAD

**Issue by jzadra** [DavisVaughan/furrr#88]
`.progress = T` does not seem to display correctly when using `future_map` functions inside  `mutate` functions for nested list columns.  They just pop up at 100% after the mutate is complete.

**Comment by DavisVaughan** [comment]
I'm not sure what the problem was here, but I'll be deprecating the progress argument in the next release as it is hacky and rarely works right. The {progressr} package has a much nicer solution
