### ISSUE TITLE
Assume stable PIDs for workers for file writing and similar tasks?

### ISSUE THREAD

**Issue by sheffe** [DavisVaughan/furrr#89]
I encounter this basic pattern all the time:
- I want to iterate over a large queue, each item yielding an output that I want to eventually write to a file (eg lines of JSON or CSV, chunks to HDF5, etc). 
- The output is large so I don't want to keep the accumulating returned values in memory, and writing interim values to a file (either a tempfile I concatenate later or append=TRUE) would be appropriate but I have to safely parallelize. 
- Writing a small file to disk for every element of `.x` and then combining them all later tends to be costly in disk I/O, and I'll admit that I never knew how large a headache could be created by writing 10M+ files to the same folder on a Mac...

A happy medium might look like this: if a worker always has its own stable PID, for N workers I generate N files and append all results for individual `.x` elements handled by that worker to that file. Then `outfile_{PID}.csv` has no chance of corruption from multiple writes, but we still get dramatically fewer intermediate files to concatenate.

Here's an example of what I mean:
```r|
library(tidyverse)
library(furrr)

plan(multisession(workers = 4))

set.seed(1234)
test_x <- rpois(10000, 100)

test_func <- function(x){
  pid <- Sys.getpid()
  some_data <- jsonlite::toJSON(list(norm = rnorm(10, mean = x, sd = x + 10)))
  write_lines(x = some_data,
              path = paste0("outfile_", pid, ".json"),
              append = TRUE)
  invisible(x)
}

furrr::future_map(test_x, test_func)
```

That snippet works fine, but it depends on workers having stable independent PIDs and I'm not sure if that's a globally true assumption about future workers. (The magic of future/furrr has been that I need not think too much about the nature of those workers.) Do you know if this is likely to be a safe-enough pattern for cases like this?

**Comment by DavisVaughan** [comment]
I'm fairly certain this won't cause race conditions where you are writing to the same file from multiple workers. It looks okay to me.
