### ISSUE TITLE
Not utilizing specified cores

### ISSUE THREAD

**Issue by jzadra** [DavisVaughan/furrr#94]
I have 16 available cores and even when set explicitly to use most of them (15), I still see activity in only every other one. 

```
availableCores()
system 
    16 
require(furrr); plan(multiprocess, workers = 15)
```

![image](https://user-images.githubusercontent.com/25590353/70164192-f7a91d80-167d-11ea-893d-2896cc5ef667.png)

Is this due to the way Mac OS X reports, or am I doing something wrong with how I'm specifying how furrr should run?

MacOS Mojave
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

**Comment by DavisVaughan** [comment]
Can you please provide a full reproducible script of what you were trying to accomplish?
