### ISSUE TITLE
How to suppress `.progress` if {furrr} was called by another package?

### ISSUE THREAD

**Issue by xiaodaigh** [DavisVaughan/furrr#96]
I am using someone else's package which uses {furrr}. It prints out this

```
Progress: ──────────────────────────────────────────────────────────────── 100%
```

which I can't suppress with `suppressMessages` because the devloper didn't make it `.progress` a parameter in their program and it's not `...` passed to `furrr`.

Now I am bit stuck. Can I suppress the `progress` in `{furrr}` some how? I tried `invisible` and `suppressMessages`

**Comment by DavisVaughan** [comment]
It uses `cat()` to output the progress bar (maybe it shouldn't), so you can technically suppress _everything_ by using `sink(tempfile())`

```r
library(furrr)
plan(multisession, workers = 2)

sink(tempfile())
future_map(1:10, ~Sys.sleep(sample(1:3, 1)), .progress = TRUE)
sink()
```

really you should request that the `.progress` parameter is passed through as an argument
