### ISSUE TITLE
performance decreased because furrr cannot access libraries loaded into global environment

### ISSUE THREAD

**Issue by agilebean** [DavisVaughan/furrr#98]
I found the reason accounting for a large part of the lower performance of furrr vs purrr:
All libraries are loaded in each individual furrr::future_map process, e.g.:
```
Loading required package: dplyr
Attaching package: ‘dplyr’
```
I understand that each furrr process requires loading the libraries, but my more pressing question is: 
_Why can't furrr access the libraries loaded in the global environment?_

Or in other words:
_Is there a way to assign libraries to the multicore/multisession/multiprocess cluster analoge to how `multidplyr` does it?_
The `multidplyr` is rather intuitive for that:
```
cluster <- new_cluster(8)
cluster_library(cluster, "dplyr")
```

**Comment by DavisVaughan** [comment]
Required packages are going to be auto-detected and loaded on the workers for you if they are required. The multidplyr way is just a more manual approach of what is done here
