### ISSUE TITLE
Problems with furrr and shell function using system()

### ISSUE THREAD

**Issue by ivanhigueram** [DavisVaughan/furrr#99]
I am currently using a `tibble` to pass parameters to a function in a orderly way and then using the `furrr::future_map()` to map a function across all the parameters. The function works flawlessly when using the sequential future, but once I try a `multicore` or `multisession` approach things start to fail. 

This is a subset of my parameters `tibble`:

```
   facility_id latitude longitude facility_name stack_height start_date duration daily_hours seq_dates  
         <dbl>    <dbl>     <dbl> <chr>                <dbl> <date>        <dbl> <list>      <list>     
 1           3     31.0     -88.0 Barry                 183. 2006-01-01       72 <dbl [4]>   <date [31]>
 2           3     31.0     -88.0 Barry                 183. 2006-02-01       72 <dbl [4]>   <date [28]>
 3           3     31.0     -88.0 Barry                 183. 2006-03-01       72 <dbl [4]>   <date [31]>
 4           3     31.0     -88.0 Barry                 183. 2006-04-01       72 <dbl [4]>   <date [30]>
 5           3     31.0     -88.0 Barry                 183. 2006-05-01       72 <dbl [4]>   <date [31]>
 6           3     31.0     -88.0 Barry                 183. 2006-06-01       72 <dbl [4]>   <date [30]>
 7           3     31.0     -88.0 Barry                 183. 2006-07-01       72 <dbl [4]>   <date [31]>
 8           3     31.0     -88.0 Barry                 183. 2006-08-01       72 <dbl [4]>   <date [31]>
 9           3     31.0     -88.0 Barry                 183. 2006-09-01       72 <dbl [4]>   <date [30]>
10           3     31.0     -88.0 Barry                 183. 2006-10-01       72 <dbl [4]>   <date [31]>
11           3     31.0     -88.0 Barry                 183. 2006-11-01       72 <dbl [4]>   <date [30]>
12           3     31.0     -88.0 Barry                 183. 2006-12-01       72 <dbl [4]>   <date [31]>
```

I cannot give the complete code for the `dirty wind::hysplit_trajectory` function, but in a nutshell the function is doing the following:

1. Looping through the the list of the Cartesian product of `seq_dates` and `daily_hours` and running a shell command using the `system()` command and outputting the results to a working directory (see the `here('Hysplit4/exec')`). 

2. Reading the output file of the shell command into R and making some data wrangling (and in the process copy it to another directory). 

3. Lastly, the function sends the `tibble` to a PostgreSQL database using `RPostgres`. For that last step I am using a `pool` connection to avoid the connection limit set by both the SQL database, and the DBI connection object. 

I am mapping the function like this: 

```
plan(sequential)
  parameter_df %>%
  mutate(model_traj =  furrr::future_pmap(list('lat' = latitude,
                               'lon' = longitude,
                               'height' = stack_height,
                               'name_source' = facility_name,
                               'id_source' = facility_id,
                               'duration' = duration,
                               'days' = seq_dates,
                               'daily_hours' = daily_hours,
                               'direction' = 'forward',
                               'met_type' = 'reanalysis',
                               'met_dir' = here::here('met'),
                               'exec_dir' = here::here("Hysplit4/exec"),
                               'cred'= list(creds)),
                           dirtywind::hysplit_trajectory,
                           .progress = TRUE)
  )
```

And everything runs fine. But, if I change to `plan(multiprocess)`, then I start to get incomplete results in my database and a series of errors and warnings in my R console that show that something in the step 2 went wrong. 

```
1: In file.copy(from = file.path(exec_dir, trajectory_files),  ... :
  problem copying /Users/topcat/epic/dirtywind/Hysplit4/exec/traj--fwd-06-01-01-00-1lat_31p0069_lon_-88p0103-hgt_182.88-72h to /Users/topcat/epic/dirtywind/Hysplit4/exec/1/traj-2020-01-03-18-25-20/traj--fwd-06-01-01-00-1lat_31p0069_lon_-88p0103-hgt_182.88-72h: No such file or directory
2: In file.copy(from = file.path(exec_dir, trajectory_files),  ... :
  problem copying /Users/topcat/epic/dirtywind/Hysplit4/exec/traj--fwd-06-01-01-18-1lat_31p0069_lon_-88p0103-hgt_182.88-72h to /Users/topcat/epic/dirtywind/Hysplit4/exec/1/traj-2020-01-03-18-25-20/traj--fwd-06-01-01-18-1lat_31p0069_lon_-88p0103-hgt_182.88-72h: No such file or directory
...
```

The shell command is not outputting any error, but somehow the file is not being created. I have been exploring how `system()` works with more detail, but I have not had any luck trying to debug this. There is any caveat when parallelizing shell routines using `futures`? In Python each shell code would run a sub-shell, but I am not sure if I am missing something in R.

**Comment by Youguang** [comment]
Hi @ivanhigueram , how did you solved this problem? future_map() does not work with system() for me too.
